// app/(app)/public-report.tsx
// Public read-only report viewer — no authentication required.
// Accessible via deeplink: deepdive://report/{token}
// or via params: /(app)/public-report?token={token}

import React, { useState, useEffect } from 'react';
import {
  View, Text, ScrollView, TouchableOpacity,
  Linking, Share, ActivityIndicator,
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@expo/vector-icons';
import Animated, { FadeIn, FadeInDown } from 'react-native-reanimated';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';
import { router, useLocalSearchParams } from 'expo-router';
import { fetchPublicReport } from '../../src/services/publicShare';
import { ResearchReport } from '../../src/types';
import { COLORS, FONTS, SPACING, RADIUS } from '../../src/constants/theme';
import { InfographicsPanel } from '../../src/components/research/InfographicCard';
import { SourceImageGallery } from '../../src/components/research/SourceImageGallery';

const DEPTH_LABELS: Record<string, string> = {
  quick: 'Quick Scan', deep: 'Deep Dive', expert: 'Expert Mode',
};

export default function PublicReportScreen() {
  const { token } = useLocalSearchParams<{ token: string }>();
  const insets = useSafeAreaInsets();
  const [report, setReport] = useState<ResearchReport | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError]   = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<'report' | 'findings' | 'sources'>('report');

  useEffect(() => {
    if (!token) { setError('Invalid report link.'); setLoading(false); return; }
    fetchPublicReport(token)
      .then(r => {
        if (!r) setError('This report is not available or has been made private.');
        else setReport(r);
      })
      .catch(() => setError('Failed to load report. Please check your connection.'))
      .finally(() => setLoading(false));
  }, [token]);

  const handleShare = async () => {
    if (!report) return;
    try {
      await Share.share({
        title: report.title,
        message: `${report.title}\n\nhttps://deepdive.app/report/${token}\n\n— Generated by DeepDive AI`,
      });
    } catch {}
  };

  const reliabilityColor =
    (report?.reliabilityScore ?? 0) >= 8 ? COLORS.success
    : (report?.reliabilityScore ?? 0) >= 6 ? COLORS.warning
    : COLORS.error;

  // ── Loading ─────────────────────────────────────────────────────────────────

  if (loading) {
    return (
      <LinearGradient colors={[COLORS.background, COLORS.backgroundCard]} style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <ActivityIndicator size="large" color={COLORS.primary} />
        <Text style={{ color: COLORS.textSecondary, fontSize: FONTS.sizes.sm, marginTop: SPACING.md }}>
          Loading public report…
        </Text>
      </LinearGradient>
    );
  }

  // ── Error ────────────────────────────────────────────────────────────────────

  if (error || !report) {
    return (
      <LinearGradient colors={[COLORS.background, COLORS.backgroundCard]} style={{ flex: 1, justifyContent: 'center', alignItems: 'center', padding: SPACING.xl }}>
        <View style={{
          width: 72, height: 72, borderRadius: 20,
          backgroundColor: `${COLORS.error}15`, alignItems: 'center', justifyContent: 'center',
          marginBottom: SPACING.lg,
        }}>
          <Ionicons name="lock-closed-outline" size={32} color={COLORS.error} />
        </View>
        <Text style={{ color: COLORS.textPrimary, fontSize: FONTS.sizes.lg, fontWeight: '800', textAlign: 'center', marginBottom: 8 }}>
          Report Unavailable
        </Text>
        <Text style={{ color: COLORS.textMuted, fontSize: FONTS.sizes.sm, textAlign: 'center', lineHeight: 20, marginBottom: SPACING.xl }}>
          {error ?? 'This report could not be loaded.'}
        </Text>
        <TouchableOpacity onPress={() => router.replace('/(app)/(tabs)/home' as any)}>
          <LinearGradient
            colors={COLORS.gradientPrimary}
            style={{ borderRadius: RADIUS.full, paddingVertical: 14, paddingHorizontal: SPACING.xl, flexDirection: 'row', alignItems: 'center', gap: 8 }}
          >
            <Ionicons name="home-outline" size={18} color="#FFF" />
            <Text style={{ color: '#FFF', fontSize: FONTS.sizes.base, fontWeight: '700' }}>Go to DeepDive AI</Text>
          </LinearGradient>
        </TouchableOpacity>
      </LinearGradient>
    );
  }

  // ── Report ───────────────────────────────────────────────────────────────────

  return (
    <LinearGradient colors={[COLORS.background, COLORS.backgroundCard]} style={{ flex: 1 }}>
      <SafeAreaView style={{ flex: 1 }} edges={['top']}>

        {/* Public banner */}
        <View style={{
          backgroundColor: `${COLORS.primary}15`,
          paddingHorizontal: SPACING.lg,
          paddingVertical: 8,
          flexDirection: 'row',
          alignItems: 'center',
          justifyContent: 'space-between',
          borderBottomWidth: 1,
          borderBottomColor: `${COLORS.primary}20`,
        }}>
          <View style={{ flexDirection: 'row', alignItems: 'center', gap: 6 }}>
            <Ionicons name="globe-outline" size={14} color={COLORS.primary} />
            <Text style={{ color: COLORS.primary, fontSize: FONTS.sizes.xs, fontWeight: '600' }}>
              Public Report · Shared via DeepDive AI
            </Text>
          </View>
          {report.publicViewCount !== undefined && report.publicViewCount > 0 && (
            <Text style={{ color: COLORS.textMuted, fontSize: FONTS.sizes.xs }}>
              {report.publicViewCount} view{report.publicViewCount !== 1 ? 's' : ''}
            </Text>
          )}
        </View>

        {/* Header */}
        <Animated.View
          entering={FadeIn.duration(400)}
          style={{
            flexDirection: 'row', alignItems: 'center',
            padding: SPACING.lg, paddingBottom: SPACING.sm,
            borderBottomWidth: 1, borderBottomColor: COLORS.border,
          }}
        >
          <View style={{ flex: 1 }}>
            <Text style={{ color: COLORS.textPrimary, fontSize: FONTS.sizes.base, fontWeight: '700' }} numberOfLines={2}>
              {report.title}
            </Text>
            <Text style={{ color: COLORS.textMuted, fontSize: FONTS.sizes.xs, marginTop: 4 }}>
              {new Date(report.createdAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
              {' · '}{DEPTH_LABELS[report.depth] ?? report.depth}
            </Text>
          </View>
          <TouchableOpacity
            onPress={handleShare}
            style={{
              width: 38, height: 38, borderRadius: 12,
              backgroundColor: COLORS.backgroundElevated,
              alignItems: 'center', justifyContent: 'center', marginLeft: SPACING.sm,
            }}
          >
            <Ionicons name="share-outline" size={20} color={COLORS.textSecondary} />
          </TouchableOpacity>
        </Animated.View>

        {/* Tabs */}
        <View style={{ flexDirection: 'row', paddingHorizontal: SPACING.lg, paddingVertical: SPACING.sm, gap: SPACING.sm }}>
          {(['report', 'findings', 'sources'] as const).map(tab => (
            <TouchableOpacity
              key={tab} onPress={() => setActiveTab(tab)}
              style={{
                flex: 1, paddingVertical: 8, borderRadius: RADIUS.md,
                backgroundColor: activeTab === tab ? COLORS.primary : COLORS.backgroundElevated,
                alignItems: 'center',
              }}
            >
              <Text style={{ color: activeTab === tab ? '#FFF' : COLORS.textMuted, fontSize: FONTS.sizes.xs, fontWeight: '600' }}>
                {tab.charAt(0).toUpperCase() + tab.slice(1)}
              </Text>
            </TouchableOpacity>
          ))}
        </View>

        <ScrollView
          contentContainerStyle={{ padding: SPACING.lg, paddingBottom: insets.bottom + 80 }}
          showsVerticalScrollIndicator={false}
        >
          {/* Stats */}
          <Animated.View entering={FadeInDown.duration(400)} style={{ flexDirection: 'row', gap: SPACING.sm, marginBottom: SPACING.lg }}>
            {[
              { label: 'Sources', value: String(report.sourcesCount), icon: 'globe-outline', color: COLORS.info },
              { label: 'Citations', value: String(report.citations.length), icon: 'link-outline', color: COLORS.primary },
              { label: 'Reliability', value: `${report.reliabilityScore}/10`, icon: 'shield-checkmark-outline', color: reliabilityColor },
            ].map(stat => (
              <View key={stat.label} style={{ flex: 1, backgroundColor: COLORS.backgroundCard, borderRadius: RADIUS.lg, padding: SPACING.sm, alignItems: 'center', borderWidth: 1, borderColor: COLORS.border }}>
                <Ionicons name={stat.icon as any} size={16} color={stat.color} />
                <Text style={{ color: stat.color, fontSize: FONTS.sizes.md, fontWeight: '800', marginTop: 4 }}>{stat.value}</Text>
                <Text style={{ color: COLORS.textMuted, fontSize: FONTS.sizes.xs, marginTop: 2 }}>{stat.label}</Text>
              </View>
            ))}
          </Animated.View>

          {/* REPORT TAB */}
          {activeTab === 'report' && (
            <>
              {/* Infographics (if available) */}
              {report.infographicData && (
                <InfographicsPanel data={report.infographicData} />
              )}

              {/* Executive Summary */}
              <Animated.View entering={FadeInDown.duration(400).delay(100)}>
                <LinearGradient
                  colors={['#1A1A35', '#12122A']}
                  style={{ borderRadius: RADIUS.xl, padding: SPACING.lg, marginBottom: SPACING.lg, borderWidth: 1, borderColor: `${COLORS.primary}25` }}
                >
                  <Text style={{ color: COLORS.textPrimary, fontSize: FONTS.sizes.base, fontWeight: '700', marginBottom: SPACING.sm }}>
                    Executive Summary
                  </Text>
                  <Text style={{ color: COLORS.textSecondary, fontSize: FONTS.sizes.sm, lineHeight: 22 }}>
                    {report.executiveSummary}
                  </Text>
                </LinearGradient>
              </Animated.View>

              {/* Sections */}
              {report.sections.map((section, i) => (
                <Animated.View
                  key={section.id ?? i}
                  entering={FadeInDown.duration(500).delay(i * 80)}
                  style={{
                    backgroundColor: COLORS.backgroundCard,
                    borderRadius: RADIUS.xl,
                    padding: SPACING.md,
                    marginBottom: SPACING.md,
                    borderWidth: 1, borderColor: COLORS.border,
                  }}
                >
                  <Text style={{ color: COLORS.textPrimary, fontSize: FONTS.sizes.base, fontWeight: '700', marginBottom: SPACING.sm }}>
                    {section.title}
                  </Text>
                  <Text style={{ color: COLORS.textSecondary, fontSize: FONTS.sizes.sm, lineHeight: 22, marginBottom: SPACING.sm }}>
                    {section.content}
                  </Text>
                  {section.bullets?.map((b, bi) => (
                    <View key={bi} style={{ flexDirection: 'row', alignItems: 'flex-start', marginBottom: 6 }}>
                      <View style={{ width: 6, height: 6, borderRadius: 3, backgroundColor: COLORS.primary, marginTop: 8, marginRight: 10 }} />
                      <Text style={{ color: COLORS.textSecondary, fontSize: FONTS.sizes.sm, lineHeight: 22, flex: 1 }}>{b}</Text>
                    </View>
                  ))}
                </Animated.View>
              ))}
            </>
          )}

          {/* FINDINGS TAB */}
          {activeTab === 'findings' && (
            <>
              {report.keyFindings.map((f, i) => (
                <View key={i} style={{ backgroundColor: COLORS.backgroundCard, borderRadius: RADIUS.lg, padding: SPACING.md, marginBottom: SPACING.sm, flexDirection: 'row', alignItems: 'flex-start', borderWidth: 1, borderColor: COLORS.border, borderLeftWidth: 3, borderLeftColor: COLORS.primary }}>
                  <View style={{ width: 24, height: 24, borderRadius: 12, backgroundColor: `${COLORS.primary}20`, alignItems: 'center', justifyContent: 'center', marginRight: SPACING.sm, flexShrink: 0 }}>
                    <Text style={{ color: COLORS.primary, fontSize: FONTS.sizes.xs, fontWeight: '700' }}>{i + 1}</Text>
                  </View>
                  <Text style={{ color: COLORS.textPrimary, fontSize: FONTS.sizes.sm, lineHeight: 20, flex: 1 }}>{f}</Text>
                </View>
              ))}
              {report.futurePredictions.map((p, i) => (
                <View key={i} style={{ backgroundColor: `${COLORS.warning}10`, borderRadius: RADIUS.lg, padding: SPACING.md, marginBottom: SPACING.sm, flexDirection: 'row', alignItems: 'flex-start', borderWidth: 1, borderColor: `${COLORS.warning}25` }}>
                  <Ionicons name="telescope-outline" size={16} color={COLORS.warning} style={{ marginRight: SPACING.sm, marginTop: 2 }} />
                  <Text style={{ color: COLORS.textSecondary, fontSize: FONTS.sizes.sm, lineHeight: 20, flex: 1 }}>{p}</Text>
                </View>
              ))}
            </>
          )}

          {/* SOURCES TAB */}
          {activeTab === 'sources' && (
            <>
              {/* Source images */}
              {(report.sourceImages?.length ?? 0) > 0 && (
                <SourceImageGallery images={report.sourceImages!} />
              )}
              {report.citations.map((c, i) => (
                <TouchableOpacity
                  key={c.id ?? i} onPress={() => Linking.openURL(c.url)} activeOpacity={0.7}
                  style={{ backgroundColor: COLORS.backgroundCard, borderRadius: RADIUS.lg, padding: SPACING.md, marginBottom: SPACING.sm, borderWidth: 1, borderColor: COLORS.border }}
                >
                  <Text style={{ color: COLORS.textPrimary, fontSize: FONTS.sizes.sm, fontWeight: '600', marginBottom: 4 }}>{c.title}</Text>
                  <Text style={{ color: COLORS.primary, fontSize: FONTS.sizes.xs, marginBottom: 4 }}>{c.source}</Text>
                  <Text style={{ color: COLORS.textMuted, fontSize: FONTS.sizes.xs, lineHeight: 16 }}>{c.snippet}</Text>
                </TouchableOpacity>
              ))}
            </>
          )}

          {/* CTA */}
          <View style={{
            marginTop: SPACING.xl, padding: SPACING.lg,
            backgroundColor: `${COLORS.primary}10`,
            borderRadius: RADIUS.xl, borderWidth: 1, borderColor: `${COLORS.primary}25`,
            alignItems: 'center',
          }}>
            <LinearGradient
              colors={COLORS.gradientPrimary}
              style={{ width: 52, height: 52, borderRadius: 16, alignItems: 'center', justifyContent: 'center', marginBottom: SPACING.md }}
            >
              <Ionicons name="sparkles" size={24} color="#FFF" />
            </LinearGradient>
            <Text style={{ color: COLORS.textPrimary, fontSize: FONTS.sizes.md, fontWeight: '800', textAlign: 'center', marginBottom: 8 }}>
              Research with AI
            </Text>
            <Text style={{ color: COLORS.textMuted, fontSize: FONTS.sizes.sm, textAlign: 'center', lineHeight: 20, marginBottom: SPACING.lg }}>
              Get comprehensive, AI-powered research reports on any topic in minutes.
            </Text>
            <TouchableOpacity
              onPress={() => router.replace('/(app)/(tabs)/home' as any)}
              activeOpacity={0.85}
            >
              <LinearGradient
                colors={COLORS.gradientPrimary}
                style={{ borderRadius: RADIUS.full, paddingVertical: 12, paddingHorizontal: SPACING.xl, flexDirection: 'row', alignItems: 'center', gap: 8 }}
              >
                <Ionicons name="telescope" size={16} color="#FFF" />
                <Text style={{ color: '#FFF', fontSize: FONTS.sizes.base, fontWeight: '700' }}>
                  Open DeepDive AI
                </Text>
              </LinearGradient>
            </TouchableOpacity>
          </View>
        </ScrollView>
      </SafeAreaView>
    </LinearGradient>
  );
}