// app/(app)/research-report.tsx
// Full research report display screen.
// Shows executive summary, all report sections, key findings,
// future predictions, citations, reliability score, and follow-up chat.

import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  Share,
  Alert,
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@expo/vector-icons';
import Animated, {
  FadeIn,
  FadeInDown,
} from 'react-native-reanimated';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router, useLocalSearchParams } from 'expo-router';
import { supabase } from '../../src/lib/supabase';
import { ReportSectionCard } from '../../src/components/research/ReportSection';
import { FollowUpChat } from '../../src/components/research/FollowUpChat';
import { LoadingOverlay } from '../../src/components/common/LoadingOverlay';
import { COLORS, FONTS, SPACING, RADIUS } from '../../src/constants/theme';
import { ResearchReport } from '../../src/types';
import { useConversation } from '../../src/hooks/useConversation';
import { useAuth } from '../../src/context/AuthContext';

const DEPTH_LABELS: Record<string, string> = {
  quick: 'Quick Scan',
  deep: 'Deep Dive',
  expert: 'Expert Mode',
};

export default function ResearchReportScreen() {
  const { reportId } = useLocalSearchParams<{ reportId: string }>();
  const { user } = useAuth();
  const [report, setReport] = useState<ResearchReport | null>(null);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState<'report' | 'findings' | 'sources'>('report');
  const [showChat, setShowChat] = useState(false);

  useEffect(() => {
    if (!reportId) return;
    loadReport();
  }, [reportId]);

  const loadReport = async () => {
    setLoading(true);
    try {
      const { data, error } = await supabase
        .from('research_reports')
        .select('*')
        .eq('id', reportId)
        .single();

      if (error || !data) {
        Alert.alert('Error', 'Could not load report.');
        router.back();
        return;
      }

      const mapped: ResearchReport = {
        id: data.id,
        userId: data.user_id,
        query: data.query,
        depth: data.depth,
        focusAreas: data.focus_areas ?? [],
        title: data.title ?? data.query,
        executiveSummary: data.executive_summary ?? '',
        sections: data.sections ?? [],
        keyFindings: data.key_findings ?? [],
        futurePredictions: data.future_predictions ?? [],
        citations: data.citations ?? [],
        statistics: data.statistics ?? [],
        searchQueries: data.search_queries ?? [],
        sourcesCount: data.sources_count ?? 0,
        reliabilityScore: data.reliability_score ?? 0,
        status: data.status,
        agentLogs: data.agent_logs ?? [],
        createdAt: data.created_at,
        completedAt: data.completed_at,
      };

      setReport(mapped);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const conversation = useConversation(report!);

  const handleShare = async () => {
    if (!report) return;
    try {
      await Share.share({
        title: report.title,
        message: `${report.title}\n\n${report.executiveSummary}\n\n— Generated by DeepDive AI`,
      });
    } catch (err) {
      console.error(err);
    }
  };

  const formatDate = (iso: string) => {
    return new Date(iso).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
    });
  };

  const reliabilityColor =
    report?.reliabilityScore && report.reliabilityScore >= 8
      ? COLORS.success
      : report?.reliabilityScore && report.reliabilityScore >= 6
      ? COLORS.warning
      : COLORS.error;

  if (loading) {
    return <LoadingOverlay visible message="Loading report..." />;
  }

  if (!report) return null;

  return (
    <LinearGradient colors={[COLORS.background, COLORS.backgroundCard]} style={{ flex: 1 }}>
      <SafeAreaView style={{ flex: 1 }}>
        {/* Header */}
        <Animated.View
          entering={FadeIn.duration(400)}
          style={{
            flexDirection: 'row',
            alignItems: 'center',
            padding: SPACING.lg,
            paddingBottom: SPACING.sm,
            borderBottomWidth: 1,
            borderBottomColor: COLORS.border,
          }}
        >
          <TouchableOpacity
            onPress={() => router.push('/(app)/(tabs)/home')}
            style={{
              width: 38, height: 38, borderRadius: 12,
              backgroundColor: COLORS.backgroundElevated,
              alignItems: 'center', justifyContent: 'center',
              marginRight: SPACING.sm,
            }}
          >
            <Ionicons name="arrow-back" size={20} color={COLORS.textSecondary} />
          </TouchableOpacity>

          <View style={{ flex: 1 }}>
            <Text style={{
              color: COLORS.textPrimary,
              fontSize: FONTS.sizes.base,
              fontWeight: '700',
            }} numberOfLines={1}>
              {report.title}
            </Text>
            <Text style={{ color: COLORS.textMuted, fontSize: FONTS.sizes.xs }}>
              {formatDate(report.createdAt)} · {DEPTH_LABELS[report.depth]}
            </Text>
          </View>

          <TouchableOpacity
            onPress={handleShare}
            style={{
              width: 38, height: 38, borderRadius: 12,
              backgroundColor: COLORS.backgroundElevated,
              alignItems: 'center', justifyContent: 'center',
            }}
          >
            <Ionicons name="share-outline" size={20} color={COLORS.textSecondary} />
          </TouchableOpacity>
        </Animated.View>

        {/* Tabs */}
        <View style={{
          flexDirection: 'row',
          paddingHorizontal: SPACING.lg,
          paddingVertical: SPACING.sm,
          gap: SPACING.sm,
        }}>
          {(['report', 'findings', 'sources'] as const).map((tab) => (
            <TouchableOpacity
              key={tab}
              onPress={() => setActiveTab(tab)}
              style={{
                flex: 1,
                paddingVertical: 8,
                borderRadius: RADIUS.md,
                backgroundColor: activeTab === tab
                  ? COLORS.primary
                  : COLORS.backgroundElevated,
                alignItems: 'center',
              }}
            >
              <Text style={{
                color: activeTab === tab ? '#FFF' : COLORS.textMuted,
                fontSize: FONTS.sizes.xs,
                fontWeight: '600',
                textTransform: 'capitalize',
              }}>
                {tab === 'findings' ? 'Key Findings' : tab.charAt(0).toUpperCase() + tab.slice(1)}
              </Text>
            </TouchableOpacity>
          ))}
        </View>

        {/* Content */}
        <ScrollView
          contentContainerStyle={{ padding: SPACING.lg, paddingBottom: 200 }}
          showsVerticalScrollIndicator={false}
        >
          {/* Stats bar */}
          <Animated.View entering={FadeInDown.duration(400)} style={{
            flexDirection: 'row',
            gap: SPACING.sm,
            marginBottom: SPACING.lg,
          }}>
            {[
              {
                label: 'Sources',
                value: String(report.sourcesCount),
                icon: 'globe-outline',
                color: COLORS.info,
              },
              {
                label: 'Citations',
                value: String(report.citations.length),
                icon: 'link-outline',
                color: COLORS.primary,
              },
              {
                label: 'Reliability',
                value: `${report.reliabilityScore}/10`,
                icon: 'shield-checkmark-outline',
                color: reliabilityColor,
              },
            ].map((stat) => (
              <View
                key={stat.label}
                style={{
                  flex: 1,
                  backgroundColor: COLORS.backgroundCard,
                  borderRadius: RADIUS.lg,
                  padding: SPACING.sm,
                  alignItems: 'center',
                  borderWidth: 1,
                  borderColor: COLORS.border,
                }}
              >
                <Ionicons name={stat.icon as any} size={16} color={stat.color} />
                <Text style={{
                  color: stat.color,
                  fontSize: FONTS.sizes.md,
                  fontWeight: '800',
                  marginTop: 4,
                }}>
                  {stat.value}
                </Text>
                <Text style={{
                  color: COLORS.textMuted,
                  fontSize: FONTS.sizes.xs,
                  marginTop: 2,
                }}>
                  {stat.label}
                </Text>
              </View>
            ))}
          </Animated.View>

          {/* TAB: REPORT */}
          {activeTab === 'report' && (
            <>
              {/* Executive Summary */}
              <Animated.View entering={FadeInDown.duration(400).delay(100)}>
                <LinearGradient
                  colors={['#1A1A35', '#12122A']}
                  style={{
                    borderRadius: RADIUS.xl,
                    padding: SPACING.lg,
                    marginBottom: SPACING.lg,
                    borderWidth: 1,
                    borderColor: `${COLORS.primary}25`,
                  }}
                >
                  <View style={{
                    flexDirection: 'row',
                    alignItems: 'center',
                    marginBottom: SPACING.md,
                  }}>
                    <LinearGradient
                      colors={COLORS.gradientPrimary}
                      style={{
                        width: 32, height: 32, borderRadius: 10,
                        alignItems: 'center', justifyContent: 'center',
                        marginRight: SPACING.sm,
                      }}
                    >
                      <Ionicons name="newspaper-outline" size={16} color="#FFF" />
                    </LinearGradient>
                    <Text style={{
                      color: COLORS.textPrimary,
                      fontSize: FONTS.sizes.base,
                      fontWeight: '700',
                    }}>
                      Executive Summary
                    </Text>
                  </View>
                  <Text style={{
                    color: COLORS.textSecondary,
                    fontSize: FONTS.sizes.sm,
                    lineHeight: 22,
                  }}>
                    {report.executiveSummary}
                  </Text>
                </LinearGradient>
              </Animated.View>

              {/* Report sections */}
              {report.sections.map((section, i) => (
                <ReportSectionCard
                  key={section.id ?? i}
                  section={section}
                  citations={report.citations}
                  index={i}
                />
              ))}
            </>
          )}

          {/* TAB: KEY FINDINGS */}
          {activeTab === 'findings' && (
            <>
              {/* Key Findings */}
              <Animated.View entering={FadeInDown.duration(400)}>
                <Text style={{
                  color: COLORS.textMuted,
                  fontSize: FONTS.sizes.xs,
                  fontWeight: '600',
                  letterSpacing: 1,
                  textTransform: 'uppercase',
                  marginBottom: SPACING.md,
                }}>
                  Key Findings
                </Text>
                {report.keyFindings.map((finding, i) => (
                  <View
                    key={i}
                    style={{
                      backgroundColor: COLORS.backgroundCard,
                      borderRadius: RADIUS.lg,
                      padding: SPACING.md,
                      marginBottom: SPACING.sm,
                      flexDirection: 'row',
                      alignItems: 'flex-start',
                      borderWidth: 1,
                      borderColor: COLORS.border,
                      borderLeftWidth: 3,
                      borderLeftColor: COLORS.primary,
                    }}
                  >
                    <View style={{
                      width: 24, height: 24, borderRadius: 12,
                      backgroundColor: `${COLORS.primary}20`,
                      alignItems: 'center', justifyContent: 'center',
                      marginRight: SPACING.sm,
                      flexShrink: 0,
                    }}>
                      <Text style={{
                        color: COLORS.primary,
                        fontSize: FONTS.sizes.xs,
                        fontWeight: '700',
                      }}>
                        {i + 1}
                      </Text>
                    </View>
                    <Text style={{
                      color: COLORS.textPrimary,
                      fontSize: FONTS.sizes.sm,
                      lineHeight: 20,
                      flex: 1,
                    }}>
                      {finding}
                    </Text>
                  </View>
                ))}
              </Animated.View>

              {/* Future Predictions */}
              {report.futurePredictions.length > 0 && (
                <Animated.View entering={FadeInDown.duration(400).delay(200)}>
                  <Text style={{
                    color: COLORS.textMuted,
                    fontSize: FONTS.sizes.xs,
                    fontWeight: '600',
                    letterSpacing: 1,
                    textTransform: 'uppercase',
                    marginBottom: SPACING.md,
                    marginTop: SPACING.lg,
                  }}>
                    Future Predictions
                  </Text>
                  {report.futurePredictions.map((pred, i) => (
                    <View
                      key={i}
                      style={{
                        backgroundColor: `${COLORS.warning}10`,
                        borderRadius: RADIUS.lg,
                        padding: SPACING.md,
                        marginBottom: SPACING.sm,
                        flexDirection: 'row',
                        alignItems: 'flex-start',
                        borderWidth: 1,
                        borderColor: `${COLORS.warning}25`,
                      }}
                    >
                      <Ionicons
                        name="telescope-outline"
                        size={16}
                        color={COLORS.warning}
                        style={{ marginRight: SPACING.sm, marginTop: 2, flexShrink: 0 }}
                      />
                      <Text style={{
                        color: COLORS.textSecondary,
                        fontSize: FONTS.sizes.sm,
                        lineHeight: 20,
                        flex: 1,
                      }}>
                        {pred}
                      </Text>
                    </View>
                  ))}
                </Animated.View>
              )}

              {/* Statistics */}
              {report.statistics.length > 0 && (
                <Animated.View entering={FadeInDown.duration(400).delay(300)}>
                  <Text style={{
                    color: COLORS.textMuted,
                    fontSize: FONTS.sizes.xs,
                    fontWeight: '600',
                    letterSpacing: 1,
                    textTransform: 'uppercase',
                    marginBottom: SPACING.md,
                    marginTop: SPACING.lg,
                  }}>
                    Key Statistics
                  </Text>
                  {report.statistics.slice(0, 10).map((stat, i) => (
                    <View
                      key={i}
                      style={{
                        backgroundColor: COLORS.backgroundCard,
                        borderRadius: RADIUS.lg,
                        padding: SPACING.md,
                        marginBottom: SPACING.sm,
                        borderWidth: 1,
                        borderColor: COLORS.border,
                      }}
                    >
                      <Text style={{
                        color: COLORS.primary,
                        fontSize: FONTS.sizes.lg,
                        fontWeight: '800',
                      }}>
                        {stat.value}
                      </Text>
                      <Text style={{
                        color: COLORS.textPrimary,
                        fontSize: FONTS.sizes.sm,
                        marginTop: 4,
                      }}>
                        {stat.context}
                      </Text>
                      <Text style={{
                        color: COLORS.textMuted,
                        fontSize: FONTS.sizes.xs,
                        marginTop: 4,
                      }}>
                        Source: {stat.source}
                      </Text>
                    </View>
                  ))}
                </Animated.View>
              )}
            </>
          )}

          {/* TAB: SOURCES */}
          {activeTab === 'sources' && (
            <Animated.View entering={FadeInDown.duration(400)}>
              <Text style={{
                color: COLORS.textMuted,
                fontSize: FONTS.sizes.xs,
                fontWeight: '600',
                letterSpacing: 1,
                textTransform: 'uppercase',
                marginBottom: SPACING.md,
              }}>
                {report.citations.length} Sources Used
              </Text>

              {report.citations.map((c, i) => (
                <View
                  key={c.id ?? i}
                  style={{
                    backgroundColor: COLORS.backgroundCard,
                    borderRadius: RADIUS.lg,
                    padding: SPACING.md,
                    marginBottom: SPACING.sm,
                    borderWidth: 1,
                    borderColor: COLORS.border,
                  }}
                >
                  <View style={{
                    flexDirection: 'row',
                    alignItems: 'flex-start',
                    marginBottom: 6,
                  }}>
                    <View style={{
                      width: 22, height: 22, borderRadius: 6,
                      backgroundColor: `${COLORS.primary}20`,
                      alignItems: 'center', justifyContent: 'center',
                      marginRight: 8, flexShrink: 0,
                    }}>
                      <Text style={{
                        color: COLORS.primary,
                        fontSize: 10,
                        fontWeight: '700',
                      }}>
                        {i + 1}
                      </Text>
                    </View>
                    <Text style={{
                      color: COLORS.textPrimary,
                      fontSize: FONTS.sizes.sm,
                      fontWeight: '600',
                      flex: 1,
                      lineHeight: 20,
                    }}>
                      {c.title}
                    </Text>
                  </View>
                  <Text style={{
                    color: COLORS.primary,
                    fontSize: FONTS.sizes.xs,
                    marginBottom: 4,
                  }}>
                    {c.source}{c.date ? ` · ${c.date}` : ''}
                  </Text>
                  <Text style={{
                    color: COLORS.textMuted,
                    fontSize: FONTS.sizes.xs,
                    lineHeight: 16,
                  }}>
                    {c.snippet}
                  </Text>
                  <Text style={{
                    color: COLORS.textMuted,
                    fontSize: FONTS.sizes.xs,
                    marginTop: 6,
                  }} numberOfLines={1}>
                    🔗 {c.url}
                  </Text>
                </View>
              ))}

              {/* Search queries used */}
              {report.searchQueries.length > 0 && (
                <View style={{ marginTop: SPACING.lg }}>
                  <Text style={{
                    color: COLORS.textMuted,
                    fontSize: FONTS.sizes.xs,
                    fontWeight: '600',
                    letterSpacing: 1,
                    textTransform: 'uppercase',
                    marginBottom: SPACING.md,
                  }}>
                    Search Queries Executed
                  </Text>
                  {report.searchQueries.map((q, i) => (
                    <View
                      key={i}
                      style={{
                        backgroundColor: COLORS.backgroundElevated,
                        borderRadius: RADIUS.md,
                        paddingHorizontal: SPACING.md,
                        paddingVertical: 8,
                        marginBottom: 6,
                        flexDirection: 'row',
                        alignItems: 'center',
                      }}
                    >
                      <Ionicons name="search-outline" size={14} color={COLORS.textMuted} style={{ marginRight: 8 }} />
                      <Text style={{
                        color: COLORS.textSecondary,
                        fontSize: FONTS.sizes.xs,
                      }}>
                        {q}
                      </Text>
                    </View>
                  ))}
                </View>
              )}
            </Animated.View>
          )}
        </ScrollView>

        {/* Follow-up chat toggle button */}
        {!showChat && (
          <View style={{
            position: 'absolute',
            bottom: 0, left: 0, right: 0,
            padding: SPACING.lg,
            paddingBottom: SPACING.xl,
          }}>
            <TouchableOpacity
              onPress={() => setShowChat(true)}
              activeOpacity={0.85}
            >
              <LinearGradient
                colors={COLORS.gradientPrimary}
                start={{ x: 0, y: 0 }}
                end={{ x: 1, y: 0 }}
                style={{
                  borderRadius: RADIUS.full,
                  paddingVertical: 14,
                  alignItems: 'center',
                  flexDirection: 'row',
                  justifyContent: 'center',
                  gap: 8,
                }}
              >
                <Ionicons name="chatbubble-ellipses-outline" size={18} color="#FFF" />
                <Text style={{
                  color: '#FFF',
                  fontSize: FONTS.sizes.base,
                  fontWeight: '700',
                }}>
                  Ask Follow-Up Questions
                </Text>
              </LinearGradient>
            </TouchableOpacity>
          </View>
        )}

        {/* Follow-up chat panel */}
        {showChat && (
          <View style={{ position: 'absolute', bottom: 0, left: 0, right: 0 }}>
            <View style={{
              flexDirection: 'row',
              justifyContent: 'flex-end',
              padding: SPACING.sm,
              backgroundColor: COLORS.backgroundCard,
              borderTopWidth: 1,
              borderTopColor: COLORS.border,
            }}>
              <TouchableOpacity onPress={() => setShowChat(false)}>
                <Ionicons name="chevron-down" size={22} color={COLORS.textMuted} />
              </TouchableOpacity>
            </View>
            <FollowUpChat
              messages={conversation.messages}
              sending={conversation.sending}
              onSend={conversation.sendMessage}
            />
          </View>
        )}
      </SafeAreaView>
    </LinearGradient>
  );
}