// src/services/podcastAudioUploadService.ts
// Part 15 — Uploads local podcast audio segments to Supabase Storage
// so workspace members on OTHER devices can stream / download them.
//
// PROBLEM BEING SOLVED:
//   Audio segments are generated by OpenAI TTS and saved to the local
//   device filesystem (expo-file-system documentDirectory).
//   Those file:/// URIs only work on the device that generated them.
//   When a podcast is shared to a workspace, other members get the
//   raw local paths which don't exist on their device → "audio unavailable".
//
// SOLUTION:
//   Before inserting into shared_podcasts, upload each segment to
//   Supabase Storage bucket "podcast-audio" and replace the local
//   file:/// path with the Supabase Storage URL.
//   Receiving devices then stream directly from the URL via expo-av
//   (expo-av supports http/https URLs natively).
//
// UPLOAD STRATEGY:
//   • Read each .mp3 as Base64 using expo-file-system.
//   • Decode with base64-arraybuffer → ArrayBuffer.
//   • Upload to Supabase Storage via supabase.storage.from().upload().
//   • Get a signed URL (1 year expiry) for playback.
//   • Store signed URLs back in the shared_podcasts row.
//
// CHUNKED CONCURRENCY:
//   Upload 3 segments at a time to avoid OOM on large podcasts.
//
// CACHING ON RECEIVING DEVICE:
//   useSharedPodcastPlayer downloads segments to local cache on first
//   play so subsequent plays are instant (handled separately in the hook).

import {
  readAsStringAsync,
  getInfoAsync,
  EncodingType,
} from 'expo-file-system/legacy';
import { decode as decodeBase64 } from 'base64-arraybuffer';
import { supabase } from '../lib/supabase';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface UploadProgress {
  uploaded:  number;
  total:     number;
  message:   string;
}

export type UploadProgressCallback = (progress: UploadProgress) => void;

// ─── Helpers ──────────────────────────────────────────────────────────────────

function isLocalPath(path: string): boolean {
  return (
    path.startsWith('file://') ||
    path.startsWith('/var/') ||
    path.startsWith('/data/') ||
    path.startsWith('/storage/') ||
    (!path.startsWith('http://') && !path.startsWith('https://'))
  );
}

function isSupabaseUrl(path: string): boolean {
  const supabaseUrl = process.env.EXPO_PUBLIC_SUPABASE_URL ?? '';
  return path.startsWith('https://') && path.includes('supabase');
}

function buildStoragePath(podcastId: string, segmentIndex: number): string {
  // Structure: podcasts/{podcastId}/segment_{index}.mp3
  return `podcasts/${podcastId}/segment_${segmentIndex}.mp3`;
}

// ─── Upload a single segment ──────────────────────────────────────────────────

async function uploadSegment(
  localPath: string,
  storagePath: string,
): Promise<{ url: string | null; error: string | null }> {
  try {
    // Verify file exists
    const info = await getInfoAsync(localPath);
    if (!info.exists) {
      return { url: null, error: `File does not exist: ${localPath}` };
    }

    // Read as Base64
    const base64 = await readAsStringAsync(localPath, {
      encoding: EncodingType.Base64,
    });

    if (!base64 || base64.length === 0) {
      return { url: null, error: 'File is empty' };
    }

    // Decode to ArrayBuffer (required by Supabase Storage in React Native)
    const arrayBuffer = decodeBase64(base64);

    // Upload to Supabase Storage
    const { error: uploadError } = await supabase.storage
      .from('podcast-audio')
      .upload(storagePath, arrayBuffer, {
        contentType: 'audio/mpeg',
        upsert:      true, // overwrite if re-sharing
        cacheControl: '31536000', // 1 year
      });

    if (uploadError) {
      console.warn('[podcastAudioUpload] upload error:', uploadError.message);
      return { url: null, error: uploadError.message };
    }

    // Get a long-lived signed URL (1 year = 31536000 seconds)
    const { data: signedData, error: signedError } = await supabase.storage
      .from('podcast-audio')
      .createSignedUrl(storagePath, 31536000);

    if (signedError || !signedData?.signedUrl) {
      // Fall back to public URL if bucket is public
      const { data: publicData } = supabase.storage
        .from('podcast-audio')
        .getPublicUrl(storagePath);
      const publicUrl = publicData?.publicUrl;
      if (publicUrl) {
        return { url: publicUrl, error: null };
      }
      return { url: null, error: signedError?.message ?? 'Could not get signed URL' };
    }

    return { url: signedData.signedUrl, error: null };
  } catch (err) {
    const msg = err instanceof Error ? err.message : 'Upload failed';
    console.warn('[podcastAudioUpload] segment error:', msg);
    return { url: null, error: msg };
  }
}

// ─── Upload all segments for a podcast ───────────────────────────────────────

export interface UploadedAudioResult {
  /** Signed Supabase Storage URLs (same length as input paths).
   *  Null entries mean that segment failed to upload. */
  uploadedUrls: (string | null)[];
  successCount: number;
  failureCount: number;
  allSucceeded: boolean;
}

export async function uploadPodcastAudioToStorage(
  podcastId:    string,
  localPaths:   string[],
  onProgress?:  UploadProgressCallback,
): Promise<UploadedAudioResult> {
  const results: (string | null)[] = new Array(localPaths.length).fill(null);
  let successCount = 0;
  let failureCount = 0;

  // Filter to only the paths that are local (not already uploaded)
  const toUpload: Array<{ index: number; path: string }> = localPaths
    .map((path, index) => ({ index, path }))
    .filter(({ path }) => path && isLocalPath(path));

  // Segments already at Supabase URLs — keep them as-is
  localPaths.forEach((path, index) => {
    if (path && !isLocalPath(path)) {
      results[index] = path;
      successCount++;
    }
  });

  if (toUpload.length === 0) {
    return {
      uploadedUrls: results,
      successCount,
      failureCount,
      allSucceeded: failureCount === 0,
    };
  }

  onProgress?.({
    uploaded: 0,
    total:    toUpload.length,
    message:  `Uploading audio to cloud (0/${toUpload.length})…`,
  });

  // Process in chunks of 3 concurrent uploads
  const CHUNK_SIZE = 3;

  for (let i = 0; i < toUpload.length; i += CHUNK_SIZE) {
    const chunk = toUpload.slice(i, i + CHUNK_SIZE);

    const chunkResults = await Promise.allSettled(
      chunk.map(({ index, path }) =>
        uploadSegment(path, buildStoragePath(podcastId, index))
          .then(result => ({ index, ...result }))
      )
    );

    for (const settled of chunkResults) {
      if (settled.status === 'fulfilled') {
        const { index, url, error } = settled.value;
        if (url && !error) {
          results[index] = url;
          successCount++;
        } else {
          console.warn(`[podcastAudioUpload] segment ${index} failed:`, error);
          failureCount++;
        }
      } else {
        failureCount++;
        console.warn('[podcastAudioUpload] chunk error:', settled.reason);
      }
    }

    const uploaded = Math.min(i + CHUNK_SIZE, toUpload.length);
    onProgress?.({
      uploaded,
      total:   toUpload.length,
      message: `Uploading audio (${uploaded}/${toUpload.length})…`,
    });
  }

  return {
    uploadedUrls: results,
    successCount,
    failureCount,
    allSucceeded: failureCount === 0,
  };
}

// ─── Download a URL to local cache (for playback on receiving device) ─────────

export async function downloadSegmentToCache(
  url:          string,
  podcastId:    string,
  segmentIndex: number,
): Promise<{ localPath: string | null; error: string | null }> {
  if (!url || !url.startsWith('http')) {
    return { localPath: url, error: null }; // already local
  }

  try {
    // Use expo-file-system legacy downloadAsync
    const { downloadAsync, cacheDirectory } = await import('expo-file-system/legacy');
    const cacheDir  = cacheDirectory ?? '';
    const localPath = `${cacheDir}podcast_${podcastId}_segment_${segmentIndex}.mp3`;

    // Check if already cached
    const { getInfoAsync: getInfo } = await import('expo-file-system/legacy');
    const info = await getInfo(localPath);
    if (info.exists) {
      return { localPath, error: null };
    }

    const result = await downloadAsync(url, localPath);
    if (result.status !== 200) {
      return { localPath: null, error: `Download failed: HTTP ${result.status}` };
    }

    return { localPath, error: null };
  } catch (err) {
    const msg = err instanceof Error ? err.message : 'Download failed';
    console.warn('[podcastAudioUpload] download error:', msg);
    // Return the original URL — expo-av can stream directly from https
    return { localPath: url, error: null };
  }
}

// ─── Check if a path/url is playable on this device ───────────────────────────

export async function isAudioPlayable(pathOrUrl: string): Promise<boolean> {
  if (!pathOrUrl) return false;

  // HTTP URLs are always "playable" by expo-av (streamed)
  if (pathOrUrl.startsWith('http://') || pathOrUrl.startsWith('https://')) {
    return true;
  }

  // Local paths — check file exists
  try {
    const { getInfoAsync: getInfo } = await import('expo-file-system/legacy');
    const info = await getInfo(pathOrUrl);
    return info.exists;
  } catch {
    return false;
  }
}

// ─── Delete uploaded segments from storage (when removing a shared podcast) ──

export async function deleteStorageSegments(
  podcastId:   string,
  segmentCount: number,
): Promise<void> {
  try {
    const paths: string[] = [];
    for (let i = 0; i < segmentCount; i++) {
      paths.push(buildStoragePath(podcastId, i));
    }
    if (paths.length === 0) return;
    await supabase.storage.from('podcast-audio').remove(paths);
  } catch (err) {
    // Non-fatal
    console.warn('[podcastAudioUpload] delete error:', err);
  }
}