// src/services/podcastTTSService.ts
// Part 39 FIX — Audio Quality actually changes the OpenAI TTS model & format.
// Part 53G — AbortSignal support.
// Part 59  — Routed through the `ai-audio-gateway` Edge Function.
//
// ── Part 59.2 FIX ───────────────────────────────────────────────────────────
//
// audioFileExists() was:
//
//     const info = await getInfoAsync(path);
//     return info.exists && ((info as any).size ?? 0) > 0;
//
// Two problems, both invisible in Expo Go and both fatal in a release build:
//
//   1. `size` is not guaranteed to be present. When the platform omitted it,
//      `?? 0 > 0` was false and a perfectly good 400 KB mp3 was reported as
//      missing. This function is what GlobalAudioEngine calls to decide whether
//      a segment is playable, so a false negative here makes the engine skip
//      the turn — audio "just doesn't play", with no error anywhere.
//
//   2. It probed the path verbatim. Audio generated by a previous install sits
//      under a container prefix that no longer exists (iOS UUID rotation,
//      Android Expo Go → standalone package change), so every check failed.
//
// It now delegates to filePaths.fileExists(), which never gates existence on a
// byte count, tries both file:// forms, and repairs a stale prefix by rebasing
// onto the current documentDirectory.
//
// Two new exports support the offline cache:
//   • resolvePodcastAudioPath(path) — the repaired path, or null
//   • getPodcastBaseDir()           — the generation root, read live
//
// Nothing about TTS generation, concurrency, retries or the gateway contract
// changed.

import {
  writeAsStringAsync,
  deleteAsync,
  EncodingType,
} from 'expo-file-system/legacy';

import { PodcastTurn, PodcastVoice } from '../types';
import { AUDIO_QUALITY_CONFIG }      from '../types/podcast_v2';
import type { AudioQuality }         from '../types/podcast_v2';
import { callGateway, GatewayError, isAbortError as isGatewayAbort } from './apiGateway';
import {
  docDir,
  ensureDir,
  fileExists as safeFileExists,
  resolveStoredPath,
} from '../lib/filePaths';

const CONCURRENCY = 3;

/**
 * Generation root, read live.
 *
 * Part 59.2: this used to be a module constant captured at import time:
 *     const PODCAST_BASE_DIR = (documentDirectory ?? '') + 'deepdive_podcasts/';
 * A module constant is fine within one launch, but it encouraged callers to
 * persist the resulting absolute path. Reading it through a function keeps the
 * "always current, never stored" rule visible at every call site.
 */
export function getPodcastBaseDir(): string {
  return `${docDir()}deepdive_podcasts/`;
}

/** True if an error is an AbortError (user cancelled). */
function isAbortError(err: unknown): boolean {
  return isGatewayAbort(err);
}

function resolveQualityParams(quality: AudioQuality = 'standard'): {
  model:  'tts-1' | 'tts-1-hd';
  format: 'mp3' | 'wav';
} {
  const cfg = AUDIO_QUALITY_CONFIG[quality] ?? AUDIO_QUALITY_CONFIG.standard;
  return { model: cfg.model, format: cfg.format };
}

export function estimateSegmentDurationMs(text: string): number {
  const words = text.trim().split(/\s+/).filter(Boolean).length;
  return Math.round((words / 150) * 60 * 1000);
}

// ─── Directory Management ─────────────────────────────────────────────────────

export function getPodcastDir(podcastId: string): string {
  return `${getPodcastBaseDir()}${podcastId}/`;
}

export function getSegmentPath(
  podcastId:    string,
  segmentIndex: number,
  quality:      AudioQuality = 'standard',
): string {
  const { format } = resolveQualityParams(quality);
  return `${getPodcastDir(podcastId)}turn_${segmentIndex}.${format}`;
}

export async function ensurePodcastDirectory(podcastId: string): Promise<string> {
  const dir = getPodcastDir(podcastId);
  await ensureDir(dir);
  return dir;
}

/**
 * Does this audio file exist and can we read it?
 *
 * Part 59.2: size-safe and prefix-repairing. See the header for why the old
 * `info.size > 0` test was actively harmful.
 */
export async function audioFileExists(path: string): Promise<boolean> {
  if (!path) return false;
  if (path.startsWith('http://') || path.startsWith('https://')) return true;
  return safeFileExists(path);
}

/**
 * Part 59.2 — the repaired absolute path for a stored segment path, or null.
 *
 * Use this anywhere you are about to hand a stored path to the audio player or
 * a file reader. It rebases a stale container prefix onto the current
 * documentDirectory and tries both file:// forms.
 */
export async function resolvePodcastAudioPath(path: string): Promise<string | null> {
  return resolveStoredPath(path);
}

export async function checkAllAudioFilesExist(paths: string[]): Promise<boolean> {
  if (!paths.length) return false;
  const results = await Promise.all(paths.map(audioFileExists));
  return results.every(Boolean);
}

export async function countAvailableSegments(paths: string[]): Promise<number> {
  const results = await Promise.all(paths.map(audioFileExists));
  return results.filter(Boolean).length;
}

export async function deletePodcastAudio(podcastId: string): Promise<void> {
  try {
    await deleteAsync(getPodcastDir(podcastId), { idempotent: true });
  } catch (err) {
    console.warn('[PodcastTTS] Failed to delete podcast audio directory:', err);
  }
}

// ─── Single-Segment TTS ───────────────────────────────────────────────────────

interface TTSResponse {
  audio:  string;   // base64
  format: string;
  bytes:  number;
}

export async function generateTurnAudio(
  text:       string,
  voice:      PodcastVoice,
  outputPath: string,
  retries     = 2,
  quality:    AudioQuality = 'standard',
  signal?:    AbortSignal,
): Promise<string> {
  const { model, format } = resolveQualityParams(quality);

  for (let attempt = 0; attempt <= retries; attempt++) {
    if (signal?.aborted) {
      const e = new Error('Aborted'); e.name = 'AbortError'; throw e;
    }

    try {
      const result = await callGateway<TTSResponse>(
        'ai-audio-gateway',
        {
          op:              'tts',
          model,
          input:           text,
          voice,
          response_format: format,
          speed:           1.0,
        },
        { signal },
      );

      if (!result?.audio || result.bytes < 100) {
        throw new Error('The audio service returned an empty clip');
      }

      // Part 59.2: make sure the directory exists before writing. A missing
      // parent directory threw an opaque "file could not be written" on Android
      // release builds when the app had been cleared between launches.
      await ensureDir(outputPath.slice(0, outputPath.lastIndexOf('/') + 1));

      await writeAsStringAsync(outputPath, result.audio, { encoding: EncodingType.Base64 });
      return outputPath;

    } catch (err) {
      if (isAbortError(err)) throw err;

      if (err instanceof GatewayError && err.isRateLimited && attempt < retries) {
        await new Promise(r => setTimeout(r, 2000 * Math.pow(2, attempt)));
        continue;
      }

      if (err instanceof GatewayError && err.isNotConfigured) {
        throw new Error('Audio generation is temporarily unavailable. Please try again later.');
      }

      if (attempt === retries) throw err;
      await new Promise(r => setTimeout(r, 1000 * (attempt + 1)));
    }
  }

  throw new Error(`Failed to generate audio after ${retries + 1} attempts`);
}

// ─── Batch TTS Generation ─────────────────────────────────────────────────────

export interface BatchProgressCallback {
  onSegmentComplete: (
    segmentIndex:  number,
    totalSegments: number,
    audioPath:     string,
    succeeded:     boolean
  ) => void;
  onProgress?: (message: string) => void;
}

export async function generateAllTurnAudio(
  turns:      PodcastTurn[],
  podcastId:  string,
  hostVoice:  PodcastVoice,
  guestVoice: PodcastVoice,
  callbacks:  BatchProgressCallback,
  quality:    AudioQuality = 'standard',
  signal?:    AbortSignal,
): Promise<string[]> {

  await ensurePodcastDirectory(podcastId);

  const audioPaths: string[] = new Array(turns.length).fill('');
  let completedCount = 0;

  for (let batchStart = 0; batchStart < turns.length; batchStart += CONCURRENCY) {
    if (signal?.aborted) {
      const e = new Error('Aborted'); e.name = 'AbortError'; throw e;
    }

    const batch = turns.slice(batchStart, batchStart + CONCURRENCY);

    callbacks.onProgress?.(
      `Generating audio: ${completedCount}/${turns.length} segments complete`
    );

    await Promise.allSettled(
      batch.map(async (turn) => {
        const outputPath = getSegmentPath(podcastId, turn.segmentIndex, quality);
        const voice      = turn.speaker === 'host' ? hostVoice : guestVoice;

        try {
          await generateTurnAudio(turn.text, voice, outputPath, 2, quality, signal);
          audioPaths[turn.segmentIndex] = outputPath;
          completedCount++;
          callbacks.onSegmentComplete(turn.segmentIndex, turns.length, outputPath, true);
        } catch (err) {
          if (isAbortError(err)) { completedCount++; return; }
          console.warn(
            `[PodcastTTS] Segment ${turn.segmentIndex} failed:`,
            err instanceof Error ? err.message : err
          );
          completedCount++;
          callbacks.onSegmentComplete(turn.segmentIndex, turns.length, '', false);
        }
      })
    );
  }

  callbacks.onProgress?.(
    `Audio generation complete: ${audioPaths.filter(Boolean).length}/${turns.length} segments`
  );

  return audioPaths;
}

export async function regenerateMissingSegments(
  turns:      PodcastTurn[],
  podcastId:  string,
  hostVoice:  PodcastVoice,
  guestVoice: PodcastVoice,
  callbacks:  BatchProgressCallback,
  quality:    AudioQuality = 'standard',
  signal?:    AbortSignal,
): Promise<string[]> {

  await ensurePodcastDirectory(podcastId);

  const existChecks = await Promise.all(
    turns.map(turn => audioFileExists(getSegmentPath(podcastId, turn.segmentIndex, quality)))
  );

  const missingTurns = turns.filter((_, i) => !existChecks[i]);

  if (missingTurns.length === 0) {
    return turns.map(t => getSegmentPath(podcastId, t.segmentIndex, quality));
  }

  callbacks.onProgress?.(`Regenerating ${missingTurns.length} missing segments...`);

  const newPaths = await generateAllTurnAudio(
    missingTurns, podcastId, hostVoice, guestVoice, callbacks, quality, signal,
  );

  return turns.map((turn, i) => {
    if (existChecks[i]) return getSegmentPath(podcastId, turn.segmentIndex, quality);
    const newPath = newPaths[missingTurns.indexOf(turn)];
    return newPath ?? '';
  });
}