// src/services/VoiceDebateAudioEngine.ts
// Part 42 UPDATE — Migrated from deprecated `expo-av` to `expo-audio`.
//
// Same migration rationale as GlobalAudioEngine.ts (see that file's header
// for the full explanation of why expo-av broke on SDK 57 and the API
// mapping). This file keeps the 3-tier local/cache/cloud URI resolution
// from Part 41.2 unchanged — only the underlying playback primitive
// (Audio.Sound → AudioPlayer) and its status-time units (ms → s) changed.
//
// NOTE: createAudioPlayer's second argument is an `AudioPlayerOptions`
// object (`{ updateInterval }`), not a bare number — passing a number
// breaks TS overload resolution and silently drops `addListener` from
// the inferred AudioPlayer type.

import { createAudioPlayer, setAudioModeAsync, type AudioPlayer, type AudioStatus } from 'expo-audio';
import { audioFileExists }                   from './voiceDebateTTSService';
import { getLocalVoiceDebateAudioPaths }     from '../lib/voiceDebateAudioCache';
import type {
  VoiceDebate,
  VoiceDebateTurn,
  DebateSegmentType,
}                                            from '../types/voiceDebate';

// ─── Engine State ─────────────────────────────────────────────────────────────

export interface VoiceDebateEngineState {
  voiceDebateId:      string | null;
  voiceDebate:        VoiceDebate | null;
  isPlaying:          boolean;
  isLoading:          boolean;
  isBuffering:        boolean;
  currentTurnIndex:   number;
  positionMs:         number;
  segmentDurationMs:  number;
  totalPositionMs:    number;
  totalDurationMs:    number;
  playbackRate:       number;
  currentSegmentType: DebateSegmentType;
  isVisible:          boolean;
  progressPercent:    number;
  pausedByOffline:    boolean;
  // Part 41.2: which source is being used right now
  audioSourceType:    'local' | 'cache' | 'cloud' | 'unknown';
}

const INITIAL_STATE: VoiceDebateEngineState = {
  voiceDebateId:      null,
  voiceDebate:        null,
  isPlaying:          false,
  isLoading:          false,
  isBuffering:        false,
  currentTurnIndex:   0,
  positionMs:         0,
  segmentDurationMs:  0,
  totalPositionMs:    0,
  totalDurationMs:    0,
  playbackRate:       1.0,
  currentSegmentType: 'opening',
  isVisible:          false,
  progressPercent:    0,
  pausedByOffline:    false,
  audioSourceType:    'unknown',
};

// ─── Singletons ───────────────────────────────────────────────────────────────

let engineState: VoiceDebateEngineState = { ...INITIAL_STATE };
let globalPlayer:      AudioPlayer | null = null;
let statusUnsubscribe: (() => void) | null = null;
let loadTurnLock                          = false;
let audioSessionReady                     = false;
let currentRate                           = 1.0;
let keepAlive                             = false;
let cumulativeMs                          = 0;

const STATUS_UPDATE_INTERVAL_MS = 250;

// Cache of resolved local paths for the current debate (avoids repeated
// filesystem checks on every turn advance)
let resolvedLocalPaths: string[] | null   = null;
let resolvedForId:      string | null     = null;

let loadTurnRef: (index: number, autoPlay: boolean) => Promise<void> = async () => {};

// ─── Subscribers ────────────────────────────────────────────────────────────

type Subscriber = (state: VoiceDebateEngineState) => void;
const subscribers = new Set<Subscriber>();

export function subscribeToVDEngine(cb: Subscriber): () => void {
  subscribers.add(cb);
  cb(engineState);
  return () => { subscribers.delete(cb); };
}

export function getVDEngineState(): VoiceDebateEngineState {
  return engineState;
}

function broadcast(partial: Partial<VoiceDebateEngineState>): void {
  engineState = { ...engineState, ...partial };
  subscribers.forEach(cb => { try { cb(engineState); } catch {} });
}

// ─── Audio Session ────────────────────────────────────────────────────────────

async function ensureAudioSession(): Promise<void> {
  if (audioSessionReady) return;
  try {
    await setAudioModeAsync({
      allowsRecording:        false,
      playsInSilentMode:      true,
      shouldPlayInBackground: false,
      interruptionMode:       'duckOthers',
    });
    audioSessionReady = true;
  } catch {}
}

// ─── Audio URI Resolution — 3-tier priority ───────────────────────────────────
//
//  Tier 1 — Local file (original device, generated by TTS)
//  Tier 2 — Local cache (downloaded copy, any device after downloadVoiceDebateAudio())
//  Tier 3 — Cloud URL (Supabase Storage, any device, requires internet)

async function resolveAudioUri(
  vd:    VoiceDebate,
  index: number,
): Promise<{ uri: string; sourceType: 'local' | 'cache' | 'cloud' } | null> {

  // ── Tier 1: original local file ──────────────────────────────────────────
  const localPath = vd.audioSegmentPaths?.[index] ?? '';
  if (localPath && !localPath.startsWith('http')) {
    if (await audioFileExists(localPath)) {
      return { uri: localPath, sourceType: 'local' };
    }
  }

  // ── Tier 2: local cache (downloaded for offline/cross-device) ────────────
  // We lazily load the cache paths list once per debate ID
  if (resolvedForId !== vd.id) {
    resolvedLocalPaths = await getLocalVoiceDebateAudioPaths(vd.id).catch(() => null);
    resolvedForId      = vd.id;
  }
  const cachePath = resolvedLocalPaths?.[index] ?? '';
  if (cachePath && await audioFileExists(cachePath)) {
    return { uri: cachePath, sourceType: 'cache' };
  }

  // ── Tier 3: cloud URL ─────────────────────────────────────────────────────
  const cloudUrl: string | null = (vd.audioStorageUrls as any)?.[index] ?? null;
  if (cloudUrl && (cloudUrl.startsWith('https://') || cloudUrl.startsWith('http://'))) {
    return { uri: cloudUrl, sourceType: 'cloud' };
  }

  // Also check if the audioSegmentPaths entry itself is an HTTPS URL
  // (happens when the debate was opened from cloud on a different device)
  if (localPath && (localPath.startsWith('https://') || localPath.startsWith('http://'))) {
    return { uri: localPath, sourceType: 'cloud' };
  }

  return null;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function getCumMs(turns: VoiceDebateTurn[], upTo: number): number {
  return turns.slice(0, upTo).reduce((s, t) => s + (t.durationMs ?? 0), 0);
}

function getTotalMs(turns: VoiceDebateTurn[]): number {
  return turns.reduce((s, t) => s + (t.durationMs ?? 0), 0);
}

function getSegmentType(vd: VoiceDebate, idx: number): DebateSegmentType {
  return vd.script?.turns?.[idx]?.segmentType ?? 'opening';
}

// ─── Status Handler ───────────────────────────────────────────────────────────
// NOTE: expo-audio reports currentTime/duration in SECONDS — converted to ms
// here so downstream state/consumers are unaffected by the migration.

function makeStatusHandler(
  vd:         VoiceDebate,
  turnIndex:  number,
  turnCumMs:  number,
  totalDurMs: number,
) {
  return (status: AudioStatus) => {
    if (!status?.isLoaded) return;

    const posMs    = Math.round((status.currentTime ?? 0) * 1000);
    const durMs    = Math.round((status.duration ?? 0) * 1000);
    const totalPos = turnCumMs + posMs;
    const progress = totalDurMs > 0 ? totalPos / totalDurMs : 0;

    broadcast({
      isLoading:          false,
      isBuffering:        status.playbackState === 'buffering',
      isPlaying:          status.playing ?? false,
      positionMs:         posMs,
      segmentDurationMs:  durMs,
      totalPositionMs:    totalPos,
      totalDurationMs:    totalDurMs,
      currentTurnIndex:   turnIndex,
      progressPercent:    progress,
      isVisible:          true,
    });

    if (status.didJustFinish) {
      const turns   = vd.script?.turns ?? [];
      const nextIdx = turnIndex + 1;
      if (nextIdx < turns.length) {
        setTimeout(() => loadTurnRef(nextIdx, true), 120);
      } else {
        broadcast({
          isPlaying:       false,
          positionMs:      0,
          totalPositionMs: totalDurMs,
          progressPercent: 1,
        });
      }
    }
  };
}

// ─── Core: Load Turn ──────────────────────────────────────────────────────────

async function loadTurn(index: number, autoPlay: boolean): Promise<void> {
  const vd = engineState.voiceDebate;
  if (!vd) return;

  const turns = vd.script?.turns ?? [];
  if (index < 0 || index >= turns.length) return;
  if (loadTurnLock) return;

  loadTurnLock = true;

  try {
    if (statusUnsubscribe) {
      try { statusUnsubscribe(); } catch {}
      statusUnsubscribe = null;
    }

    cumulativeMs     = getCumMs(turns, index);
    const totalDurMs = getTotalMs(turns);
    const segType    = getSegmentType(vd, index);

    broadcast({
      currentTurnIndex:   index,
      isLoading:          true,
      positionMs:         0,
      segmentDurationMs:  0,
      totalPositionMs:    cumulativeMs,
      totalDurationMs:    totalDurMs,
      progressPercent:    totalDurMs > 0 ? cumulativeMs / totalDurMs : 0,
      currentSegmentType: segType,
    });

    const resolved = await resolveAudioUri(vd, index);

    if (!resolved) {
      broadcast({ isLoading: false });
      loadTurnLock = false;
      if (autoPlay && index < turns.length - 1) {
        setTimeout(() => loadTurnRef(index + 1, true), 80);
      }
      return;
    }

    // Log which source we're using (helpful for debugging cross-device issues)
    if (resolved.sourceType === 'cloud') {
      console.log(`[VDEngine] 🌐  Turn ${index}: streaming from cloud`);
    } else if (resolved.sourceType === 'cache') {
      console.log(`[VDEngine] 💾  Turn ${index}: playing from local cache`);
    }

    const handler = makeStatusHandler(vd, index, cumulativeMs, totalDurMs);

    if (!globalPlayer) {
      globalPlayer = createAudioPlayer({ uri: resolved.uri }, { updateInterval: STATUS_UPDATE_INTERVAL_MS });
    } else {
      globalPlayer.replace({ uri: resolved.uri });
    }

    globalPlayer.setPlaybackRate(currentRate);

    const subscription = globalPlayer.addListener('playbackStatusUpdate', handler);
    statusUnsubscribe = () => subscription.remove();

    if (autoPlay) {
      globalPlayer.play();
    }

    broadcast({
      isLoading:       false,
      isPlaying:       autoPlay,
      isVisible:       true,
      voiceDebateId:   vd.id,
      voiceDebate:     vd,
      audioSourceType: resolved.sourceType,
    });

    loadTurnLock = false;
  } catch (err) {
    console.warn(`[VDEngine] Turn ${index} error:`, err);
    broadcast({ isLoading: false });
    loadTurnLock = false;
    if (autoPlay && (engineState.voiceDebate?.script?.turns?.length ?? 0) > index + 1) {
      setTimeout(() => loadTurnRef(index + 1, true), 300);
    }
  }
}

loadTurnRef = loadTurn;

// ─── Public API ───────────────────────────────────────────────────────────────

export const VoiceDebateEngine = {

  isActiveFor(voiceDebateId: string): boolean {
    return engineState.voiceDebateId === voiceDebateId && globalPlayer !== null;
  },

  // ── Part 41.2: Offline pause ──────────────────────────────────────────────

  async pauseForOffline(): Promise<void> {
    if (!globalPlayer) return;
    if (!engineState.isPlaying) return;
    try {
      globalPlayer.pause();
      broadcast({ isPlaying: false, pausedByOffline: true });
    } catch (err) {
      console.warn('[VDEngine] pauseForOffline error:', err);
    }
  },

  clearOfflinePause(): void {
    if (engineState.pausedByOffline) {
      broadcast({ pausedByOffline: false });
    }
  },

  // ── Core ──────────────────────────────────────────────────────────────────

  async start(vd: VoiceDebate, fromTurnIndex = 0): Promise<void> {
    await ensureAudioSession();
    keepAlive = false;

    // Reset cache resolution state for fresh debate
    resolvedLocalPaths = null;
    resolvedForId      = null;

    const turns      = vd.script?.turns ?? [];
    const totalDurMs = getTotalMs(turns);

    broadcast({
      voiceDebateId:    vd.id,
      voiceDebate:      vd,
      isVisible:        true,
      totalDurationMs:  totalDurMs,
      currentTurnIndex: fromTurnIndex,
      pausedByOffline:  false,
      audioSourceType:  'unknown',
    });

    await loadTurn(fromTurnIndex, true);
  },

  async reattach(vd: VoiceDebate): Promise<void> {
    if (!globalPlayer) return;
    broadcast({ voiceDebate: vd, voiceDebateId: vd.id });

    const turns      = vd.script?.turns ?? [];
    const totalDurMs = getTotalMs(turns);
    const idx        = engineState.currentTurnIndex;

    if (statusUnsubscribe) {
      try { statusUnsubscribe(); } catch {}
      statusUnsubscribe = null;
    }
    const handler = makeStatusHandler(vd, idx, cumulativeMs, totalDurMs);
    const subscription = globalPlayer.addListener('playbackStatusUpdate', handler);
    statusUnsubscribe = () => subscription.remove();

    try {
      const posMs    = Math.round((globalPlayer.currentTime ?? 0) * 1000);
      const durMs    = Math.round((globalPlayer.duration ?? 0) * 1000);
      const totalPos = cumulativeMs + posMs;
      broadcast({
        isPlaying:          globalPlayer.playing ?? false,
        isLoading:          false,
        isBuffering:        false,
        positionMs:         posMs,
        segmentDurationMs:  durMs,
        totalPositionMs:    totalPos,
        totalDurationMs:    totalDurMs > 0 ? totalDurMs : engineState.totalDurationMs,
        progressPercent:    totalDurMs > 0 ? totalPos / totalDurMs : engineState.progressPercent,
        currentTurnIndex:   idx,
        isVisible:          true,
      });
    } catch {}
  },

  async play(): Promise<void> {
    if (!globalPlayer) return;
    try {
      globalPlayer.play();
      broadcast({ isPlaying: true, pausedByOffline: false });
    } catch {}
  },

  async pause(): Promise<void> {
    if (!globalPlayer) return;
    try {
      globalPlayer.pause();
      broadcast({ isPlaying: false, pausedByOffline: false });
    } catch {}
  },

  async toggle(): Promise<void> {
    if (!globalPlayer) return;
    try {
      if (globalPlayer.playing) {
        globalPlayer.pause();
        broadcast({ isPlaying: false, pausedByOffline: false });
      } else {
        globalPlayer.play();
        broadcast({ isPlaying: true, pausedByOffline: false });
      }
    } catch {}
  },

  async skipToTurn(index: number): Promise<void> {
    const wasPlaying = engineState.isPlaying;
    await loadTurn(index, wasPlaying);
  },

  async skipNext(): Promise<void> {
    const turns = engineState.voiceDebate?.script?.turns ?? [];
    const next  = engineState.currentTurnIndex + 1;
    if (next < turns.length) await this.skipToTurn(next);
  },

  async skipPrevious(): Promise<void> {
    if (globalPlayer) {
      try {
        const posMs = Math.round((globalPlayer.currentTime ?? 0) * 1000);
        if (posMs > 2500) {
          globalPlayer.seekTo(0);
          broadcast({ positionMs: 0, totalPositionMs: cumulativeMs });
          return;
        }
      } catch {}
    }
    const prev = engineState.currentTurnIndex - 1;
    if (prev >= 0) await this.skipToTurn(prev);
  },

  async setRate(rate: number): Promise<void> {
    currentRate = rate;
    broadcast({ playbackRate: rate });
    if (globalPlayer) {
      try { globalPlayer.setPlaybackRate(rate); } catch {}
    }
  },

  async seekToPercent(percent: number): Promise<void> {
    const vd = engineState.voiceDebate;
    if (!vd) return;
    const turns    = vd.script?.turns ?? [];
    const totalDur = getTotalMs(turns);
    const targetMs = percent * totalDur;
    let cum = 0;
    for (let i = 0; i < turns.length; i++) {
      const dur = turns[i].durationMs ?? 0;
      if (cum + dur >= targetMs || i === turns.length - 1) {
        await this.skipToTurn(i);
        return;
      }
      cum += dur;
    }
  },

  detach(): void { keepAlive = true; },

  async stop(): Promise<void> {
    keepAlive    = false;
    loadTurnLock = false;

    if (statusUnsubscribe) {
      try { statusUnsubscribe(); } catch {}
      statusUnsubscribe = null;
    }

    if (globalPlayer) {
      try {
        globalPlayer.pause();
        globalPlayer.remove();
      } catch {}
      globalPlayer = null;
    }

    resolvedLocalPaths = null;
    resolvedForId      = null;
    cumulativeMs       = 0;
    broadcast({ ...INITIAL_STATE, isVisible: false });
  },

  get shouldKeepAlive(): boolean { return keepAlive; },
  set shouldKeepAlive(v: boolean) { keepAlive = v; },

  formatTime(ms: number): string {
    const totalSec = Math.floor(Math.max(0, ms) / 1000);
    return `${Math.floor(totalSec / 60)}:${(totalSec % 60).toString().padStart(2, '0')}`;
  },
};

export function isVDEngineActiveFor(id: string): boolean {
  return VoiceDebateEngine.isActiveFor(id);
}