// src/services/agents/moderatorAgent.ts
// Part 9 — Moderator Agent
//
// Receives all agent perspectives and synthesises them into a balanced
// moderated summary. This agent does NOT search the web — it works
// exclusively from the perspectives already generated by the debate agents.
//
// Output: DebateModerator with sections matching the research output spec:
//   • Perspective Comparison (summary)
//   • Arguments For
//   • Arguments Against
//   • Neutral Conclusion
//   • Consensus Points
//   • Key Tensions
//   • Balanced Verdict

import { chatCompletionJSON } from '../openaiClient';
import { DebatePerspective, DebateModerator } from '../../types';

// ─── Perspective serialiser ───────────────────────────────────────────────────

function serialisePerspectives(perspectives: DebatePerspective[]): string {
  return perspectives
    .map(p => {
      const stanceDisplay = p.stanceType.replace(/_/g, ' ').toUpperCase();
      const argsText = p.arguments
        .map(a => `  • [${a.strength.toUpperCase()}] ${a.point}\n    ${a.evidence}`)
        .join('\n');

      return `
══════════════════════════════════════
${p.agentName} (${p.tagline})
Stance: "${p.stanceLabel}"
Position: ${stanceDisplay}
Confidence: ${p.confidence}/10

SUMMARY:
${p.summary}

ARGUMENTS:
${argsText}

KEY QUOTE:
"${p.keyQuote}"
══════════════════════════════════════`.trim();
    })
    .join('\n\n');
}

// ─── Raw output type ──────────────────────────────────────────────────────────

interface ModeratorRaw {
  summary:           string;
  argumentsFor:      string[];
  argumentsAgainst:  string[];
  neutralConclusion: string;
  consensusPoints:   string[];
  keyTensions:       string[];
  balancedVerdict:   string;
}

// ─── Main export ──────────────────────────────────────────────────────────────

export async function runModeratorAgent(
  topic:        string,
  question:     string,
  perspectives: DebatePerspective[],
): Promise<DebateModerator> {
  const serialised = serialisePerspectives(perspectives);

  const stanceBreakdown = perspectives
    .map(p => `${p.agentName}: ${p.stanceType.replace(/_/g, ' ')} (confidence ${p.confidence}/10)`)
    .join('\n');

  const systemPrompt =
`You are a world-class debate moderator — the calibre you would see chairing debates at the Oxford Union, Davos, or the UN. Your role is to synthesise multiple expert perspectives into a balanced, analytically rigorous summary.

Your synthesis must:
- Accurately represent each perspective without distortion
- Identify genuine consensus versus superficial agreement
- Surface the deepest, most fundamental tensions
- Draw a nuanced conclusion that respects complexity
- Never take a partisan position yourself
- Be specific: reference agents by name, cite their arguments and quotes

You write with precision, intellectual authority, and genuine balance.`;

  const userPrompt =
`DEBATE TOPIC: "${topic}"
CENTRAL QUESTION: "${question}"

STANCE OVERVIEW:
${stanceBreakdown}

FULL PERSPECTIVES (${perspectives.length} agents):
${serialised}

─────────────────────────────────────────────

As Moderator, produce a comprehensive synthesis of this debate.

Return ONLY valid JSON with NO markdown fences:
{
  "summary": "4 substantial paragraphs synthesising all perspectives. Para 1: Overview of the debate landscape and where agents cluster. Para 2: Deep analysis of the strongest arguments across all sides. Para 3: Where perspectives fundamentally diverge and why. Para 4: What a reasonable, informed observer should take away. Reference specific agents and their quotes.",

  "argumentsFor": [
    "Strongest argument in favour — attribute to the agent who made it most powerfully, with their evidence (1-2 sentences)",
    "Second argument in favour with attribution",
    "Third argument in favour with attribution",
    "Fourth argument in favour with attribution"
  ],

  "argumentsAgainst": [
    "Strongest argument against — attribute to the agent, with evidence",
    "Second argument against with attribution",
    "Third argument against with attribution",
    "Fourth argument against with attribution"
  ],

  "neutralConclusion": "3 paragraphs. Para 1: The core truth that emerges from this debate. Para 2: Conditions under which the optimistic outcome is more likely vs the pessimistic one. Para 3: What evidence or milestones would help settle this debate. Do not take sides — give readers the analytical tools to form their own view.",

  "consensusPoints": [
    "A point that most or all agents agree on, even if they draw different conclusions from it",
    "Second consensus point",
    "Third consensus point"
  ],

  "keyTensions": [
    "The deepest fundamental disagreement — what makes this debate genuinely hard",
    "Second major tension point",
    "Third tension point"
  ],

  "balancedVerdict": "One single sentence (< 35 words) that honestly captures the state of the debate without picking a winner. This should be quotable and intellectually honest."
}`;

  const raw = await chatCompletionJSON<ModeratorRaw>(
    [
      { role: 'system', content: systemPrompt },
      { role: 'user',   content: userPrompt },
    ],
    { temperature: 0.35, maxTokens: 3500 },
  );

  // Validate and return with safe fallbacks
  return {
    summary:           raw.summary           ?? '',
    argumentsFor:      Array.isArray(raw.argumentsFor)      ? raw.argumentsFor.slice(0, 5)      : [],
    argumentsAgainst:  Array.isArray(raw.argumentsAgainst)  ? raw.argumentsAgainst.slice(0, 5)  : [],
    neutralConclusion: raw.neutralConclusion ?? '',
    consensusPoints:   Array.isArray(raw.consensusPoints)   ? raw.consensusPoints.slice(0, 4)   : [],
    keyTensions:       Array.isArray(raw.keyTensions)       ? raw.keyTensions.slice(0, 4)       : [],
    balancedVerdict:   raw.balancedVerdict   ?? '',
  };
}