// src/components/research/ShareSheet.tsx
// Fixes:
//  • Deep-link sent exactly ONCE — iOS Share.share appends `url` to `message`
//    automatically, so we pass ONLY `url` (no link in message text).
//    On Android there is no `url` field so we pass ONLY `message` with the link.
//  • Link is clickable — deepdiveai://report/{token} is the only URL sent,
//    and it is registered as the app scheme in app.json, so the OS renders it
//    as a tappable link in iMessage, WhatsApp, Telegram, etc.

import React, { useState } from 'react';
import {
  View, Text, TouchableOpacity, Modal, Share,
  ActivityIndicator, Platform,
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@expo/vector-icons';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import * as Clipboard from 'expo-clipboard';
import { ResearchReport } from '../../types';
import { usePublicShare } from '../../hooks/usePublicShare';
import { useAuth } from '../../context/AuthContext';
import { COLORS, FONTS, SPACING, RADIUS } from '../../constants/theme';

interface Props {
  visible: boolean;
  report: ResearchReport;
  onClose: () => void;
}

export function ShareSheet({ visible, report, onClose }: Props) {
  const { user }  = useAuth();
  const insets    = useSafeAreaInsets();
  const {
    shareInfo, isPublic, loading, checking,
    enable, disable, copyLink, getOrCreateLink,
  } = usePublicShare(report.id, user?.id ?? '');

  const [copied, setCopied] = useState(false);

  // ── Text-only summary (no link) ───────────────────────────────────────────

  const handleNativeShare = async () => {
    try {
      await Share.share({
        title:   report.title,
        message: `${report.title}\n\n${report.executiveSummary.slice(0, 300)}…\n\n— Generated by DeepDive AI`,
      });
    } catch {}
  };

  // ── Share with deep-link — exactly once, clickable ───────────────────────
  //
  // The iOS Share sheet CONCATENATES message + url when both are provided,
  // which is what caused the duplicate. The fix:
  //
  //   iOS   → pass { url: appLink }  only — the OS appends it once automatically.
  //           Add a plain-text title/message WITHOUT the link so the preview
  //           looks nice in iMessage.
  //
  //   Android → pass { message: appLink }  only — Android ignores the `url` field.
  //
  // Result: the recipient sees the link exactly once, and because deepdiveai://
  // is registered in app.json, messaging apps render it as a tappable hyperlink.

  const handleShareWithLink = async () => {
    const appLink = await getOrCreateLink(); // deepdiveai://report/{token}
    if (!appLink) return;

    try {
      if (Platform.OS === 'ios') {
        await Share.share({
          title:   report.title,
          // message is the preview text shown above the link in iMessage etc.
          // It must NOT contain the URL or iOS will show it twice.
          message: `${report.title} — shared via DeepDive AI`,
          url:     appLink,   // iOS renders this as the clickable link
        });
      } else {
        // Android: only message is used; url field is silently ignored
        await Share.share({
          title:   report.title,
          message: appLink,   // send the link alone so it's the cleanest tap target
        });
      }
    } catch {}
  };

  // ── Copy to clipboard ─────────────────────────────────────────────────────

  const handleCopyLink = async () => {
    await copyLink(); // copies deepdiveai://report/{token}
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  // ── Toggle public / private ───────────────────────────────────────────────

  const handleTogglePublic = async () => {
    if (isPublic) await disable();
    else await enable();
  };

  // Short display label shown under "Copy Link"
  const displayLabel = shareInfo?.token
    ? `deepdiveai://report/${shareInfo.token.slice(0, 10)}…`
    : 'Generates a shareable app link';

  return (
    <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}>
      {/* Backdrop */}
      <TouchableOpacity
        style={{ flex: 1, backgroundColor: 'rgba(0,0,0,0.55)' }}
        activeOpacity={1}
        onPress={onClose}
      />

      {/* Sheet */}
      <View style={{
        position: 'absolute', bottom: 0, left: 0, right: 0,
        backgroundColor: COLORS.backgroundCard,
        borderTopLeftRadius: RADIUS.xl * 1.5,
        borderTopRightRadius: RADIUS.xl * 1.5,
        paddingBottom: insets.bottom + SPACING.md,
        borderTopWidth: 1, borderTopColor: COLORS.border,
      }}>

        {/* Handle */}
        <View style={{
          width: 40, height: 4, borderRadius: 2,
          backgroundColor: COLORS.border,
          alignSelf: 'center',
          marginTop: SPACING.sm, marginBottom: SPACING.lg,
        }} />

        <View style={{ paddingHorizontal: SPACING.lg }}>

          {/* Header */}
          <Text style={{ color: COLORS.textPrimary, fontSize: FONTS.sizes.md, fontWeight: '800', marginBottom: 4 }}>
            Share Report
          </Text>
          <Text style={{ color: COLORS.textMuted, fontSize: FONTS.sizes.xs, marginBottom: SPACING.lg }} numberOfLines={1}>
            {report.title}
          </Text>

          <View style={{ gap: SPACING.sm }}>

            {/* 1 — Text summary only */}
            <TouchableOpacity
              onPress={handleNativeShare}
              style={{
                flexDirection: 'row', alignItems: 'center',
                backgroundColor: COLORS.backgroundElevated,
                borderRadius: RADIUS.lg, padding: SPACING.md,
                borderWidth: 1, borderColor: COLORS.border,
              }}
            >
              <View style={{
                width: 44, height: 44, borderRadius: 12,
                backgroundColor: `${COLORS.info}15`,
                alignItems: 'center', justifyContent: 'center', marginRight: SPACING.md,
              }}>
                <Ionicons name="chatbubble-outline" size={22} color={COLORS.info} />
              </View>
              <View style={{ flex: 1 }}>
                <Text style={{ color: COLORS.textPrimary, fontSize: FONTS.sizes.base, fontWeight: '600' }}>
                  Share Summary
                </Text>
                <Text style={{ color: COLORS.textMuted, fontSize: FONTS.sizes.xs, marginTop: 2 }}>
                  Title + summary as text, no link
                </Text>
              </View>
              <Ionicons name="chevron-forward" size={16} color={COLORS.textMuted} />
            </TouchableOpacity>

            {/* 2 — Share app link (once, clickable) */}
            <TouchableOpacity
              onPress={handleShareWithLink}
              disabled={loading}
              style={{
                flexDirection: 'row', alignItems: 'center',
                backgroundColor: COLORS.backgroundElevated,
                borderRadius: RADIUS.lg, padding: SPACING.md,
                borderWidth: 1, borderColor: COLORS.border,
              }}
            >
              <LinearGradient
                colors={COLORS.gradientPrimary}
                style={{
                  width: 44, height: 44, borderRadius: 12,
                  alignItems: 'center', justifyContent: 'center', marginRight: SPACING.md,
                }}
              >
                {loading
                  ? <ActivityIndicator size="small" color="#FFF" />
                  : <Ionicons name="link" size={22} color="#FFF" />
                }
              </LinearGradient>
              <View style={{ flex: 1 }}>
                <Text style={{ color: COLORS.textPrimary, fontSize: FONTS.sizes.base, fontWeight: '600' }}>
                  Share App Link
                </Text>
                <Text style={{ color: COLORS.textMuted, fontSize: FONTS.sizes.xs, marginTop: 2 }}>
                  Recipient taps once → opens DeepDive AI
                </Text>
              </View>
              <Ionicons name="chevron-forward" size={16} color={COLORS.textMuted} />
            </TouchableOpacity>

            {/* 3 — Copy link */}
            <TouchableOpacity
              onPress={handleCopyLink}
              disabled={loading}
              style={{
                flexDirection: 'row', alignItems: 'center',
                backgroundColor: COLORS.backgroundElevated,
                borderRadius: RADIUS.lg, padding: SPACING.md,
                borderWidth: 1,
                borderColor: copied ? `${COLORS.success}40` : COLORS.border,
              }}
            >
              <View style={{
                width: 44, height: 44, borderRadius: 12,
                backgroundColor: copied ? `${COLORS.success}15` : `${COLORS.primary}15`,
                alignItems: 'center', justifyContent: 'center', marginRight: SPACING.md,
              }}>
                <Ionicons
                  name={copied ? 'checkmark-circle' : 'copy-outline'}
                  size={22}
                  color={copied ? COLORS.success : COLORS.primary}
                />
              </View>
              <View style={{ flex: 1 }}>
                <Text style={{ color: copied ? COLORS.success : COLORS.textPrimary, fontSize: FONTS.sizes.base, fontWeight: '600' }}>
                  {copied ? 'Copied!' : 'Copy Link'}
                </Text>
                <Text style={{ color: COLORS.textMuted, fontSize: FONTS.sizes.xs, marginTop: 2 }} numberOfLines={1}>
                  {displayLabel}
                </Text>
              </View>
            </TouchableOpacity>

          </View>

          {/* Public / Private toggle */}
          <View style={{
            marginTop: SPACING.lg, padding: SPACING.md,
            backgroundColor: COLORS.backgroundElevated,
            borderRadius: RADIUS.lg,
            borderWidth: 1,
            borderColor: isPublic ? `${COLORS.primary}30` : COLORS.border,
          }}>
            <View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}>
              <View style={{ flex: 1, marginRight: SPACING.md }}>
                <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 4 }}>
                  <View style={{
                    width: 8, height: 8, borderRadius: 4,
                    backgroundColor: isPublic ? COLORS.success : COLORS.textMuted,
                  }} />
                  <Text style={{ color: COLORS.textPrimary, fontSize: FONTS.sizes.sm, fontWeight: '700' }}>
                    {isPublic ? 'Public Report' : 'Private Report'}
                  </Text>
                </View>
                <Text style={{ color: COLORS.textMuted, fontSize: FONTS.sizes.xs, lineHeight: 16 }}>
                  {isPublic
                    ? `Anyone with the link can view · ${shareInfo?.viewCount ?? 0} view${shareInfo?.viewCount !== 1 ? 's' : ''}`
                    : 'Only you can see this report'
                  }
                </Text>
              </View>

              <TouchableOpacity
                onPress={handleTogglePublic}
                disabled={loading || checking}
                style={{
                  backgroundColor: isPublic ? `${COLORS.primary}20` : COLORS.backgroundCard,
                  borderRadius: RADIUS.full,
                  paddingHorizontal: 14, paddingVertical: 8,
                  borderWidth: 1,
                  borderColor: isPublic ? COLORS.primary : COLORS.border,
                  minWidth: 96, alignItems: 'center',
                }}
              >
                {loading || checking
                  ? <ActivityIndicator size="small" color={COLORS.primary} />
                  : <Text style={{
                      color: isPublic ? COLORS.primary : COLORS.textMuted,
                      fontSize: FONTS.sizes.xs, fontWeight: '700',
                    }}>
                      {isPublic ? 'Make Private' : 'Make Public'}
                    </Text>
                }
              </TouchableOpacity>
            </View>
          </View>

          {/* Close */}
          <TouchableOpacity
            onPress={onClose}
            style={{
              marginTop: SPACING.md, paddingVertical: 14,
              backgroundColor: COLORS.backgroundElevated,
              borderRadius: RADIUS.lg, alignItems: 'center',
              borderWidth: 1, borderColor: COLORS.border,
            }}
          >
            <Text style={{ color: COLORS.textMuted, fontSize: FONTS.sizes.base, fontWeight: '600' }}>
              Close
            </Text>
          </TouchableOpacity>

        </View>
      </View>
    </Modal>
  );
}