// src/components/research/ShareSheet.tsx
// Advanced share-summary sheet.
// Removed: app link, copy link, public/private toggle.
// Added: 5 rich text formats with preview, copy-text, and native share.

import React, { useState } from 'react';
import {
  View, Text, TouchableOpacity, Modal, Share,
  ScrollView, ActivityIndicator, Platform,
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@expo/vector-icons';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import * as Clipboard from 'expo-clipboard';
import Animated, { FadeInDown } from 'react-native-reanimated';
import { ResearchReport } from '../../types';
import { COLORS, FONTS, SPACING, RADIUS } from '../../constants/theme';

interface Props {
  visible: boolean;
  report: ResearchReport;
  onClose: () => void;
}

// ─── Text format builders ─────────────────────────────────────────────────────

function buildQuickSummary(r: ResearchReport): string {
  const date = new Date(r.createdAt).toLocaleDateString('en-US', {
    month: 'short', day: 'numeric', year: 'numeric',
  });
  const depth = r.depth.charAt(0).toUpperCase() + r.depth.slice(1);
  const summary = r.executiveSummary.length > 420
    ? r.executiveSummary.slice(0, 420) + '…'
    : r.executiveSummary;
  return [
    `📊 ${r.title}`,
    `📅 ${date}  ·  🔍 ${depth} Research`,
    '',
    summary,
    '',
    `📚 ${r.sourcesCount} sources  ·  ✅ Reliability: ${r.reliabilityScore}/10`,
    '',
    '— Generated by DeepDive AI',
  ].join('\n');
}

function buildFullBrief(r: ResearchReport): string {
  const lines = [
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    '📊 RESEARCH BRIEF',
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    `Topic:   ${r.title}`,
    `Depth:   ${r.depth.charAt(0).toUpperCase() + r.depth.slice(1)}`,
    `Sources: ${r.sourcesCount}  |  Reliability: ${r.reliabilityScore}/10`,
    '',
    '📋 EXECUTIVE SUMMARY',
    '─────────────────────',
    r.executiveSummary,
    '',
  ];
  if (r.sections.length > 0) {
    lines.push('📑 SECTIONS COVERED', '─────────────────────');
    r.sections.forEach((s, i) => lines.push(`${i + 1}. ${s.title}`));
    lines.push('');
  }
  if (r.keyFindings.length > 0) {
    lines.push('🔑 KEY FINDINGS', '─────────────────────');
    r.keyFindings.slice(0, 5).forEach((f, i) => lines.push(`${i + 1}. ${f}`));
    lines.push('');
  }
  lines.push('— Generated by DeepDive AI');
  return lines.join('\n');
}

function buildKeyFindings(r: ResearchReport): string {
  const lines = [
    `🔑 Key Findings`,
    `Topic: ${r.title}`,
    '─────────────────────────────',
    '',
  ];
  if (r.keyFindings.length > 0) {
    r.keyFindings.forEach((f, i) => lines.push(`${i + 1}. ${f}`));
  } else {
    lines.push('No key findings available.');
  }
  if (r.futurePredictions.length > 0) {
    lines.push('', '🔭 Future Outlook:');
    r.futurePredictions.slice(0, 3).forEach(p => lines.push(`• ${p}`));
  }
  lines.push('', '— Generated by DeepDive AI');
  return lines.join('\n');
}

function buildStatsSnapshot(r: ResearchReport): string {
  if (r.statistics.length === 0) return buildQuickSummary(r);
  const lines = [
    `📈 Statistics Snapshot`,
    `Topic: ${r.title}`,
    '─────────────────────────────',
    '',
  ];
  r.statistics.slice(0, 8).forEach(s => {
    lines.push(`▸ ${s.value}`);
    lines.push(`  ${s.context}`);
    lines.push(`  Source: ${s.source}`);
    lines.push('');
  });
  lines.push('— Generated by DeepDive AI');
  return lines.join('\n');
}

function buildSocialDigest(r: ResearchReport): string {
  const maxBody = 240 - r.title.length;
  const body = (r.keyFindings[0] ?? r.executiveSummary);
  const trimmed = body.length > maxBody ? body.slice(0, maxBody) + '…' : body;
  return [
    `📊 ${r.title}`,
    '',
    trimmed,
    '',
    '#AIResearch #DeepDiveAI',
  ].join('\n');
}

// ─── Format config ────────────────────────────────────────────────────────────

interface Fmt {
  id: string;
  label: string;
  desc: string;
  icon: string;
  color: string;
  gradient: readonly [string, string];
  build: (r: ResearchReport) => string;
}

const FORMATS: Fmt[] = [
  {
    id: 'quick',
    label: 'Quick Summary',
    desc: 'Title, summary & reliability score',
    icon: 'flash-outline',
    color: '#6C63FF',
    gradient: ['#6C63FF', '#8B5CF6'],
    build: buildQuickSummary,
  },
  {
    id: 'full',
    label: 'Full Research Brief',
    desc: 'Summary, sections & key findings',
    icon: 'document-text-outline',
    color: '#4FACFE',
    gradient: ['#4FACFE', '#00F2FE'],
    build: buildFullBrief,
  },
  {
    id: 'findings',
    label: 'Key Findings',
    desc: 'Numbered findings + future outlook',
    icon: 'bulb-outline',
    color: '#43E97B',
    gradient: ['#43E97B', '#38F9D7'],
    build: buildKeyFindings,
  },
  {
    id: 'stats',
    label: 'Statistics Snapshot',
    desc: 'Data points & figures only',
    icon: 'stats-chart-outline',
    color: '#FA709A',
    gradient: ['#FA709A', '#FEE140'],
    build: buildStatsSnapshot,
  },
  {
    id: 'social',
    label: 'Social Digest',
    desc: 'Short-form, hashtag-ready (~280 chars)',
    icon: 'megaphone-outline',
    color: '#F093FB',
    gradient: ['#F093FB', '#F5576C'],
    build: buildSocialDigest,
  },
];

// ─── Component ────────────────────────────────────────────────────────────────

export function ShareSheet({ visible, report, onClose }: Props) {
  const insets = useSafeAreaInsets();
  const [selectedId, setSelected] = useState('quick');
  const [sharing,    setSharing]  = useState(false);
  const [copied,     setCopied]   = useState(false);
  const [showPrev,   setShowPrev] = useState(false);

  const fmt = FORMATS.find(f => f.id === selectedId) ?? FORMATS[0];
  const preview = fmt.build(report);
  const charCount = preview.length;

  const handleShare = async () => {
    setSharing(true);
    try {
      await Share.share({ title: report.title, message: preview });
    } catch {}
    setSharing(false);
  };

  const handleCopy = async () => {
    await Clipboard.setStringAsync(preview);
    setCopied(true);
    setTimeout(() => setCopied(false), 2200);
  };

  return (
    <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}>
      {/* Backdrop */}
      <TouchableOpacity
        style={{ flex: 1, backgroundColor: 'rgba(0,0,0,0.6)' }}
        activeOpacity={1}
        onPress={onClose}
      />

      {/* Sheet */}
      <View style={{
        position: 'absolute', bottom: 0, left: 0, right: 0,
        backgroundColor: COLORS.backgroundCard,
        borderTopLeftRadius: 28, borderTopRightRadius: 28,
        paddingBottom: insets.bottom + SPACING.md,
        borderTopWidth: 1, borderTopColor: COLORS.border,
        maxHeight: '88%',
      }}>

        {/* Handle */}
        <View style={{
          width: 40, height: 4, borderRadius: 2,
          backgroundColor: COLORS.border,
          alignSelf: 'center',
          marginTop: SPACING.sm, marginBottom: SPACING.md,
        }} />

        <ScrollView
          showsVerticalScrollIndicator={false}
          contentContainerStyle={{ paddingHorizontal: SPACING.lg, paddingBottom: SPACING.md }}
          keyboardShouldPersistTaps="handled"
        >
          {/* Header */}
          <View style={{ marginBottom: SPACING.lg }}>
            <Text style={{
              color: COLORS.textPrimary, fontSize: FONTS.sizes.lg, fontWeight: '800',
            }}>
              Share Report
            </Text>
            <Text
              style={{ color: COLORS.textMuted, fontSize: FONTS.sizes.xs, marginTop: 3 }}
              numberOfLines={1}
            >
              {report.title}
            </Text>
          </View>

          {/* Format label */}
          <Text style={{
            color: COLORS.textMuted, fontSize: FONTS.sizes.xs, fontWeight: '600',
            letterSpacing: 1, textTransform: 'uppercase', marginBottom: SPACING.sm,
          }}>
            Choose Format
          </Text>

          {/* Format cards */}
          <View style={{ gap: SPACING.sm, marginBottom: SPACING.lg }}>
            {FORMATS.map((f, i) => {
              const active = f.id === selectedId;
              const chars  = f.build(report).length;
              return (
                <Animated.View key={f.id} entering={FadeInDown.duration(300).delay(i * 45)}>
                  <TouchableOpacity
                    onPress={() => { setSelected(f.id); setShowPrev(false); }}
                    activeOpacity={0.8}
                    style={{
                      flexDirection: 'row', alignItems: 'center',
                      backgroundColor: active ? `${f.color}12` : COLORS.backgroundElevated,
                      borderRadius: RADIUS.lg, padding: SPACING.md,
                      borderWidth: 1.5,
                      borderColor: active ? f.color : COLORS.border,
                    }}
                  >
                    <LinearGradient
                      colors={active ? f.gradient : ['#2A2A4A', '#1A1A35']}
                      style={{
                        width: 44, height: 44, borderRadius: 12,
                        alignItems: 'center', justifyContent: 'center',
                        marginRight: SPACING.md, flexShrink: 0,
                      }}
                    >
                      <Ionicons
                        name={f.icon as any}
                        size={20}
                        color={active ? '#FFF' : COLORS.textMuted}
                      />
                    </LinearGradient>

                    <View style={{ flex: 1 }}>
                      <Text style={{
                        color: active ? COLORS.textPrimary : COLORS.textSecondary,
                        fontSize: FONTS.sizes.base, fontWeight: '700',
                      }}>
                        {f.label}
                      </Text>
                      <Text style={{ color: COLORS.textMuted, fontSize: FONTS.sizes.xs, marginTop: 2 }}>
                        {f.desc}
                      </Text>
                    </View>

                    <View style={{ alignItems: 'flex-end', gap: 4 }}>
                      <Text style={{ color: COLORS.textMuted, fontSize: 10 }}>
                        ~{chars < 1000 ? chars : `${(chars / 1000).toFixed(1)}k`} chars
                      </Text>
                      {active && (
                        <View style={{
                          width: 18, height: 18, borderRadius: 9,
                          backgroundColor: f.color,
                          alignItems: 'center', justifyContent: 'center',
                        }}>
                          <Ionicons name="checkmark" size={11} color="#FFF" />
                        </View>
                      )}
                    </View>
                  </TouchableOpacity>
                </Animated.View>
              );
            })}
          </View>

          {/* Preview toggle */}
          <TouchableOpacity
            onPress={() => setShowPrev(p => !p)}
            style={{
              flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6,
              paddingVertical: 9,
              backgroundColor: COLORS.backgroundElevated,
              borderRadius: RADIUS.md,
              borderWidth: 1, borderColor: COLORS.border,
              marginBottom: showPrev ? SPACING.sm : SPACING.lg,
            }}
          >
            <Ionicons
              name={showPrev ? 'eye-off-outline' : 'eye-outline'}
              size={15}
              color={COLORS.textMuted}
            />
            <Text style={{ color: COLORS.textMuted, fontSize: FONTS.sizes.xs, fontWeight: '600' }}>
              {showPrev ? 'Hide Preview' : 'Preview Content'}
            </Text>
          </TouchableOpacity>

          {/* Preview box */}
          {showPrev && (
            <Animated.View
              entering={FadeInDown.duration(280)}
              style={{
                backgroundColor: '#0E0E22',
                borderRadius: RADIUS.lg,
                padding: SPACING.md,
                marginBottom: SPACING.lg,
                borderWidth: 1,
                borderColor: `${fmt.color}35`,
                maxHeight: 200,
              }}
            >
              {/* Toolbar */}
              <View style={{
                flexDirection: 'row', alignItems: 'center',
                justifyContent: 'space-between',
                marginBottom: SPACING.sm,
              }}>
                <Text style={{ color: fmt.color, fontSize: FONTS.sizes.xs, fontWeight: '700' }}>
                  {fmt.label}
                </Text>
                <Text style={{ color: COLORS.textMuted, fontSize: 10 }}>
                  {charCount} chars
                </Text>
              </View>
              <ScrollView showsVerticalScrollIndicator={false} nestedScrollEnabled>
                <Text style={{
                  color: COLORS.textSecondary,
                  fontSize: FONTS.sizes.xs,
                  lineHeight: 18,
                  fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
                }}>
                  {preview}
                </Text>
              </ScrollView>
            </Animated.View>
          )}

          {/* Action row */}
          <View style={{ flexDirection: 'row', gap: SPACING.sm }}>

            {/* Copy text */}
            <TouchableOpacity
              onPress={handleCopy}
              style={{
                flex: 1, paddingVertical: 14, borderRadius: RADIUS.lg,
                backgroundColor: copied ? `${COLORS.success}15` : COLORS.backgroundElevated,
                alignItems: 'center', justifyContent: 'center',
                flexDirection: 'row', gap: 7,
                borderWidth: 1,
                borderColor: copied ? `${COLORS.success}40` : COLORS.border,
              }}
            >
              <Ionicons
                name={copied ? 'checkmark-circle' : 'copy-outline'}
                size={17}
                color={copied ? COLORS.success : COLORS.textSecondary}
              />
              <Text style={{
                color: copied ? COLORS.success : COLORS.textSecondary,
                fontSize: FONTS.sizes.sm, fontWeight: '700',
              }}>
                {copied ? 'Copied!' : 'Copy'}
              </Text>
            </TouchableOpacity>

            {/* Share */}
            <TouchableOpacity
              onPress={handleShare}
              disabled={sharing}
              activeOpacity={0.85}
              style={{ flex: 2.2 }}
            >
              <LinearGradient
                colors={fmt.gradient}
                start={{ x: 0, y: 0 }} end={{ x: 1, y: 0 }}
                style={{
                  paddingVertical: 14, borderRadius: RADIUS.lg,
                  alignItems: 'center', justifyContent: 'center',
                  flexDirection: 'row', gap: 8,
                }}
              >
                {sharing
                  ? <ActivityIndicator size="small" color="#FFF" />
                  : <Ionicons name="share-outline" size={17} color="#FFF" />
                }
                <Text style={{ color: '#FFF', fontSize: FONTS.sizes.sm, fontWeight: '800' }}>
                  {sharing ? 'Sharing…' : `Share ${fmt.label}`}
                </Text>
              </LinearGradient>
            </TouchableOpacity>

          </View>

          {/* Close */}
          <TouchableOpacity
            onPress={onClose}
            style={{
              marginTop: SPACING.sm, paddingVertical: 13,
              backgroundColor: COLORS.backgroundElevated,
              borderRadius: RADIUS.lg, alignItems: 'center',
              borderWidth: 1, borderColor: COLORS.border,
            }}
          >
            <Text style={{ color: COLORS.textMuted, fontSize: FONTS.sizes.sm, fontWeight: '600' }}>
              Close
            </Text>
          </TouchableOpacity>

        </ScrollView>
      </View>
    </Modal>
  );
}