// src/components/research/ShareSheet.tsx
// ─────────────────────────────────────────────────────────────────────────────
// Share Sheet — FULL THEME COMPATIBILITY
// ─────────────────────────────────────────────────────────────────────────────

import React, { useState } from 'react';
import {
  View, Text, Pressable, Modal, Share,
  ScrollView, ActivityIndicator, Platform,
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@expo/vector-icons';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import * as Clipboard from 'expo-clipboard';
import Animated, { FadeInDown } from 'react-native-reanimated';
import { ResearchReport } from '../../types';
import { COLORS, FONTS, SPACING, RADIUS, getModalBackdrop } from '../../constants/theme';
import { useTheme } from '../../context/ThemeContext';

interface Props {
  visible: boolean;
  report: ResearchReport;
  onClose: () => void;
}

function buildQuickSummary(r: ResearchReport): string {
  const date = new Date(r.createdAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  const depth = r.depth.charAt(0).toUpperCase() + r.depth.slice(1);
  const summary = r.executiveSummary.length > 420 ? r.executiveSummary.slice(0, 420) + '…' : r.executiveSummary;
  return [
    `📊 ${r.title}`,
    `📅 ${date}  ·  🔍 ${depth} Research`,
    '',
    summary,
    '',
    `📚 ${r.sourcesCount} sources  ·  ✅ Reliability: ${r.reliabilityScore}/10`,
    '',
    '— Generated by DeepDive AI',
  ].join('\n');
}

function buildFullBrief(r: ResearchReport): string {
  const lines = [
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    '📊 RESEARCH BRIEF',
    '━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    `Topic:   ${r.title}`,
    `Depth:   ${r.depth.charAt(0).toUpperCase() + r.depth.slice(1)}`,
    `Sources: ${r.sourcesCount}  |  Reliability: ${r.reliabilityScore}/10`,
    '',
    '📋 EXECUTIVE SUMMARY',
    '─────────────────────',
    r.executiveSummary,
    '',
  ];
  if (r.sections.length > 0) {
    lines.push('📑 SECTIONS COVERED', '─────────────────────');
    r.sections.forEach((s, i) => lines.push(`${i + 1}. ${s.title}`));
    lines.push('');
  }
  if (r.keyFindings.length > 0) {
    lines.push('🔑 KEY FINDINGS', '─────────────────────');
    r.keyFindings.slice(0, 5).forEach((f, i) => lines.push(`${i + 1}. ${f}`));
    lines.push('');
  }
  lines.push('— Generated by DeepDive AI');
  return lines.join('\n');
}

function buildKeyFindings(r: ResearchReport): string {
  const lines = [`🔑 Key Findings`, `Topic: ${r.title}`, '─────────────────────────────', ''];
  if (r.keyFindings.length > 0) r.keyFindings.forEach((f, i) => lines.push(`${i + 1}. ${f}`));
  else lines.push('No key findings available.');
  if (r.futurePredictions.length > 0) {
    lines.push('', '🔭 Future Outlook:');
    r.futurePredictions.slice(0, 3).forEach(p => lines.push(`• ${p}`));
  }
  lines.push('', '— Generated by DeepDive AI');
  return lines.join('\n');
}

function buildStatsSnapshot(r: ResearchReport): string {
  if (r.statistics.length === 0) return buildQuickSummary(r);
  const lines = [`📈 Statistics Snapshot`, `Topic: ${r.title}`, '─────────────────────────────', ''];
  r.statistics.slice(0, 8).forEach(s => {
    lines.push(`▸ ${s.value}`, `  ${s.context}`, `  Source: ${s.source}`, '');
  });
  lines.push('— Generated by DeepDive AI');
  return lines.join('\n');
}

function buildSocialDigest(r: ResearchReport): string {
  const maxBody = 240 - r.title.length;
  const body = r.keyFindings[0] ?? r.executiveSummary;
  const trimmed = body.length > maxBody ? body.slice(0, maxBody) + '…' : body;
  return [`📊 ${r.title}`, '', trimmed, '', '#AIResearch #DeepDiveAI'].join('\n');
}

interface Fmt {
  id: string; label: string; desc: string; icon: string; color: string;
  gradient: readonly [string, string]; build: (r: ResearchReport) => string;
}

const FORMATS: Fmt[] = [
  { id: 'quick', label: 'Quick Summary', desc: 'Title, summary & reliability score', icon: 'flash-outline', color: '#6C63FF', gradient: ['#6C63FF', '#8B5CF6'] as const, build: buildQuickSummary },
  { id: 'full', label: 'Full Research Brief', desc: 'Summary, sections & key findings', icon: 'document-text-outline', color: '#4FACFE', gradient: ['#4FACFE', '#00F2FE'] as const, build: buildFullBrief },
  { id: 'findings', label: 'Key Findings', desc: 'Numbered findings + future outlook', icon: 'bulb-outline', color: '#43E97B', gradient: ['#43E97B', '#38F9D7'] as const, build: buildKeyFindings },
  { id: 'stats', label: 'Statistics Snapshot', desc: 'Data points & figures only', icon: 'stats-chart-outline', color: '#FA709A', gradient: ['#FA709A', '#FEE140'] as const, build: buildStatsSnapshot },
  { id: 'social', label: 'Social Digest', desc: 'Short-form, hashtag-ready (~280 chars)', icon: 'megaphone-outline', color: '#F093FB', gradient: ['#F093FB', '#F5576C'] as const, build: buildSocialDigest },
];

export function ShareSheet({ visible, report, onClose }: Props) {
  const insets = useSafeAreaInsets();
  const { isLight } = useTheme();
  const [selectedId, setSelected] = useState('quick');
  const [sharing, setSharing] = useState(false);
  const [copied, setCopied] = useState(false);
  const [showPrev, setShowPrev] = useState(false);

  const fmt = FORMATS.find(f => f.id === selectedId) ?? FORMATS[0];
  const preview = fmt.build(report);
  const charCount = preview.length;

  const handleShare = async () => {
    setSharing(true);
    try { await Share.share({ title: report.title, message: preview }); } catch {}
    setSharing(false);
  };

  const handleCopy = async () => {
    await Clipboard.setStringAsync(preview);
    setCopied(true);
    setTimeout(() => setCopied(false), 2200);
  };

  const bgGradient: readonly [string, string] = isLight ? ['#F5F6FB', '#FFFFFF'] : ['#181834', '#0C0C1C'];
  const previewBg = isLight ? '#FFFFFF' : '#0A0A1C';

  return (
    <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}>
      <Pressable style={{ flex: 1, backgroundColor: getModalBackdrop(0.6) }} onPress={onClose} />

      <View style={{
        position: 'absolute', bottom: 0, left: 0, right: 0,
        borderTopLeftRadius: 30, borderTopRightRadius: 30,
        overflow: 'hidden', maxHeight: '90%',
        borderTopWidth: 1, borderColor: `${COLORS.primary}30`,
      }}>
        <LinearGradient colors={bgGradient} style={{ paddingBottom: insets.bottom + SPACING.md }}>
          <View style={{ width: 42, height: 4, borderRadius: 2, backgroundColor: COLORS.border, alignSelf: 'center', marginTop: SPACING.sm, marginBottom: SPACING.md }} />

          <ScrollView
            showsVerticalScrollIndicator={false}
            contentContainerStyle={{ paddingHorizontal: SPACING.lg, paddingBottom: SPACING.md }}
            keyboardShouldPersistTaps="handled"
          >
            <View style={{ flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: SPACING.lg }}>
              <LinearGradient colors={fmt.gradient} style={{ width: 44, height: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }}>
                <Ionicons name="share-social" size={20} color="#FFF" />
              </LinearGradient>
              <View style={{ flex: 1 }}>
                <Text style={{ color: COLORS.textPrimary, fontSize: FONTS.sizes.lg, fontWeight: '900' }}>Share Report</Text>
                <Text style={{ color: COLORS.textMuted, fontSize: FONTS.sizes.xs, marginTop: 2 }} numberOfLines={1}>{report.title}</Text>
              </View>
            </View>

            <Text style={labelStyle()}>Choose Format</Text>

            <View style={{ gap: SPACING.sm, marginBottom: SPACING.lg }}>
              {FORMATS.map((f, i) => {
                const active = f.id === selectedId;
                const chars = f.build(report).length;
                const bgColor = active ? `${f.color}14` : (isLight ? 'rgba(0,0,0,0.03)' : 'rgba(255,255,255,0.03)');
                return (
                  <Animated.View key={f.id} entering={FadeInDown.duration(300).delay(i * 45)}>
                    <Pressable
                      onPress={() => { setSelected(f.id); setShowPrev(false); }}
                      style={{
                        flexDirection: 'row', alignItems: 'center',
                        backgroundColor: bgColor,
                        borderRadius: RADIUS.lg, padding: SPACING.md,
                        borderWidth: 1.5, borderColor: active ? f.color : COLORS.border,
                      }}
                    >
                      <LinearGradient
                        colors={active ? f.gradient : [COLORS.backgroundElevated, COLORS.backgroundCard] as readonly [string, string]}
                        style={{ width: 46, height: 46, borderRadius: 13, alignItems: 'center', justifyContent: 'center', marginRight: SPACING.md, flexShrink: 0 }}
                      >
                        <Ionicons name={f.icon as any} size={21} color={active ? '#FFF' : COLORS.textMuted} />
                      </LinearGradient>
                      <View style={{ flex: 1 }}>
                        <Text style={{ color: active ? COLORS.textPrimary : COLORS.textSecondary, fontSize: FONTS.sizes.base, fontWeight: '800' }}>{f.label}</Text>
                        <Text style={{ color: COLORS.textMuted, fontSize: FONTS.sizes.xs, marginTop: 2 }}>{f.desc}</Text>
                      </View>
                      <View style={{ alignItems: 'flex-end', gap: 5 }}>
                        <Text style={{ color: COLORS.textMuted, fontSize: 10 }}>
                          ~{chars < 1000 ? chars : `${(chars / 1000).toFixed(1)}k`}
                        </Text>
                        {active && (
                          <View style={{ width: 20, height: 20, borderRadius: 10, backgroundColor: f.color, alignItems: 'center', justifyContent: 'center' }}>
                            <Ionicons name="checkmark" size={12} color="#FFF" />
                          </View>
                        )}
                      </View>
                    </Pressable>
                  </Animated.View>
                );
              })}
            </View>

            <Pressable
              onPress={() => setShowPrev(p => !p)}
              style={{
                flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingVertical: 10,
                backgroundColor: isLight ? 'rgba(0,0,0,0.03)' : 'rgba(255,255,255,0.03)',
                borderRadius: RADIUS.md, borderWidth: 1, borderColor: COLORS.border, marginBottom: showPrev ? SPACING.sm : SPACING.lg,
              }}
            >
              <Ionicons name={showPrev ? 'eye-off-outline' : 'eye-outline'} size={15} color={COLORS.textSecondary} />
              <Text style={{ color: COLORS.textSecondary, fontSize: FONTS.sizes.xs, fontWeight: '700' }}>
                {showPrev ? 'Hide Preview' : 'Preview Content'}
              </Text>
            </Pressable>

            {showPrev && (
              <Animated.View
                entering={FadeInDown.duration(280)}
                style={{ backgroundColor: previewBg, borderRadius: RADIUS.lg, padding: SPACING.md, marginBottom: SPACING.lg, borderWidth: 1, borderColor: `${fmt.color}3A`, maxHeight: 210 }}
              >
                <View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: SPACING.sm }}>
                  <View style={{ flexDirection: 'row', alignItems: 'center', gap: 6 }}>
                    <View style={{ width: 7, height: 7, borderRadius: 4, backgroundColor: fmt.color }} />
                    <Text style={{ color: fmt.color, fontSize: FONTS.sizes.xs, fontWeight: '800' }}>{fmt.label}</Text>
                  </View>
                  <Text style={{ color: COLORS.textMuted, fontSize: 10 }}>{charCount} chars</Text>
                </View>
                <ScrollView showsVerticalScrollIndicator={false} nestedScrollEnabled>
                  <Text style={{ color: COLORS.textSecondary, fontSize: FONTS.sizes.xs, lineHeight: 18, fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace' }}>
                    {preview}
                  </Text>
                </ScrollView>
              </Animated.View>
            )}

            <View style={{ flexDirection: 'row', gap: SPACING.sm }}>
              <Pressable
                onPress={handleCopy}
                style={{
                  flex: 1, paddingVertical: 15, borderRadius: RADIUS.lg,
                  backgroundColor: copied ? `${COLORS.success}18` : (isLight ? 'rgba(0,0,0,0.03)' : 'rgba(255,255,255,0.04)'),
                  alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 7,
                  borderWidth: 1, borderColor: copied ? `${COLORS.success}44` : COLORS.border,
                }}
              >
                <Ionicons name={copied ? 'checkmark-circle' : 'copy-outline'} size={17} color={copied ? COLORS.success : COLORS.textSecondary} />
                <Text style={{ color: copied ? COLORS.success : COLORS.textSecondary, fontSize: FONTS.sizes.sm, fontWeight: '800' }}>{copied ? 'Copied!' : 'Copy'}</Text>
              </Pressable>

              <Pressable onPress={handleShare} disabled={sharing} style={{ flex: 2.2 }}>
                <LinearGradient
                  colors={fmt.gradient}
                  start={{ x: 0, y: 0 }} end={{ x: 1, y: 0 }}
                  style={{ paddingVertical: 15, borderRadius: RADIUS.lg, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8 }}
                >
                  {sharing ? <ActivityIndicator size="small" color="#FFF" /> : <Ionicons name="share-outline" size={17} color="#FFF" />}
                  <Text style={{ color: '#FFF', fontSize: FONTS.sizes.sm, fontWeight: '900' }}>{sharing ? 'Sharing…' : `Share ${fmt.label}`}</Text>
                </LinearGradient>
              </Pressable>
            </View>

            <Pressable
              onPress={onClose}
              style={{ marginTop: SPACING.sm, paddingVertical: 13, backgroundColor: isLight ? 'rgba(0,0,0,0.03)' : 'rgba(255,255,255,0.03)', borderRadius: RADIUS.lg, alignItems: 'center', borderWidth: 1, borderColor: COLORS.border }}
            >
              <Text style={{ color: COLORS.textMuted, fontSize: FONTS.sizes.sm, fontWeight: '700' }}>Close</Text>
            </Pressable>
          </ScrollView>
        </LinearGradient>
      </View>
    </Modal>
  );
}

function labelStyle() {
  return {
    color: COLORS.textMuted,
    fontSize: FONTS.sizes.xs,
    fontWeight: '700' as const,
    letterSpacing: 1,
    textTransform: 'uppercase' as const,
    marginBottom: SPACING.sm,
  };
}