-- =============================================================================
-- schema_part32_complete.sql
-- DeepDive AI — Part 32 — Admin Dashboard Upgrades (COMPLETE — All Patches)
--
-- This is the single authoritative migration for Part 32.
-- It replaces all of the following individual files — do NOT run those separately:
--   schema_part32.sql
--   schema_patch_part32_deleted_status.sql
--   schema_patch_part32_fix_test_orders.sql
--   schema_patch_part32_credit_stats_rpc.sql
--
-- Prerequisites: Parts 1–31 schema already applied (especially Part 31 admin tables).
-- Safe to run multiple times — every statement is idempotent.
-- Does NOT modify existing user data or break any existing RLS policies.
--
-- Run in: Supabase Dashboard → SQL Editor → New Query → Paste → Run
-- =============================================================================

-- ══════════════════════════════════════════════════════════════════════════════
-- SECTION 1 — PROFILES: account_status extended to include 'deleted'
--
-- WHY:
--   The admin DELETE route sets account_status = 'deleted' BEFORE calling
--   auth.admin.deleteUser(). This fires a Realtime UPDATE event to the user's
--   app while their JWT is still valid, so the AccountDeletedScreen shows
--   immediately. Without 'deleted' in the allowed values, the UPDATE fails.
--
-- The CHECK constraint from Part 31 is dropped and recreated with 'deleted'.
-- If no constraint existed, only the ALTER TABLE runs (idempotent via IF NOT EXISTS).
-- ══════════════════════════════════════════════════════════════════════════════

-- Ensure account_status column exists (Part 31 already adds this — no-op if present)
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS account_status TEXT NOT NULL DEFAULT 'active';

-- Backfill any NULL values (safety net for old rows)
UPDATE public.profiles
SET account_status = 'active'
WHERE account_status IS NULL;

-- Drop old constraint (name may vary) and recreate with 'deleted' included
DO $$
BEGIN
  ALTER TABLE public.profiles
    DROP CONSTRAINT IF EXISTS profiles_account_status_check;
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE public.profiles
    DROP CONSTRAINT IF EXISTS account_status_check;
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_account_status_check
  CHECK (account_status IN ('active', 'suspended', 'flagged', 'deleted'));

COMMENT ON COLUMN public.profiles.account_status IS
  'Admin-controlled account status: '
  'active (default) | suspended (locked) | flagged (review marker) | deleted (being deleted by admin)';

-- ══════════════════════════════════════════════════════════════════════════════
-- SECTION 2 — RAZORPAY ORDERS: is_test flag
--
-- WHY:
--   Allows the admin Payments page to toggle between live-only and all orders.
--   Revenue stat cards always exclude test orders regardless of the toggle.
--   The updated razorpay-create-order edge function sets is_test = true when
--   the Razorpay key starts with 'rzp_test_'.
--   All existing rows default to false (treated as live — backward compatible).
-- ══════════════════════════════════════════════════════════════════════════════

ALTER TABLE public.razorpay_orders
  ADD COLUMN IF NOT EXISTS is_test BOOLEAN NOT NULL DEFAULT FALSE;

-- Backfill any NULL values (safety net)
UPDATE public.razorpay_orders
SET is_test = FALSE
WHERE is_test IS NULL;

COMMENT ON COLUMN public.razorpay_orders.is_test IS
  'TRUE when order was created with a Razorpay test key (rzp_test_*). '
  'Existing rows default to FALSE (treated as live). '
  'New test orders are tagged by the updated razorpay-create-order edge function.';

-- ══════════════════════════════════════════════════════════════════════════════
-- SECTION 3 — ABUSE SIGNALS TABLE
--
-- Stores automated abuse detection signals generated by detect_abuse_signals().
-- Written only by RPCs (SECURITY DEFINER). No user access via RLS.
-- Signals are reviewed by admins via the Abuse Detection dashboard page.
-- ══════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.abuse_signals (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  signal_type   TEXT        NOT NULL,
  -- 'credit_burn_rate' | 'failed_payments' | 'referral_farming' | 'manual'

  severity      TEXT        NOT NULL DEFAULT 'medium',
  -- 'low' | 'medium' | 'high' | 'critical'

  details       JSONB       NOT NULL DEFAULT '{}'::jsonb,
  -- Context: credits_consumed_24h, failed_count, referral_count, threshold, window_hours

  is_reviewed   BOOLEAN     NOT NULL DEFAULT FALSE,
  reviewed_by   UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
  reviewed_at   TIMESTAMPTZ,
  review_action TEXT,
  -- 'cleared' | 'warned' | 'suspended'
  review_note   TEXT,

  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for fast admin queries
CREATE INDEX IF NOT EXISTS idx_abuse_signals_user_id
  ON public.abuse_signals(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_abuse_signals_pending
  ON public.abuse_signals(is_reviewed, created_at DESC)
  WHERE is_reviewed = FALSE;

CREATE INDEX IF NOT EXISTS idx_abuse_signals_type
  ON public.abuse_signals(signal_type, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_abuse_signals_severity
  ON public.abuse_signals(severity, is_reviewed);

-- RLS: enabled, no policies for authenticated role → deny all regular users.
-- Service role (admin API routes) bypasses RLS entirely.
ALTER TABLE public.abuse_signals ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.abuse_signals IS
  'Automated abuse detection signals. Admin-only access via service role.';

-- ══════════════════════════════════════════════════════════════════════════════
-- SECTION 4 — ENABLE REALTIME on profiles + user_credits
--
-- WHY:
--   The React Native app subscribes to postgres_changes on these tables:
--   • profiles UPDATE  → handles suspension, flagging, and deletion signals
--   • profiles UPDATE (account_status='deleted') → shows AccountDeletedScreen
--   • user_credits UPDATE → instantly updates credit balance in the app header
--
-- If the Supabase project restricts ALTER PUBLICATION via SQL Editor,
-- enable manually: Dashboard → Database → Replication → supabase_realtime
--   toggle ON: public.profiles and public.user_credits
-- ══════════════════════════════════════════════════════════════════════════════

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname    = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename  = 'profiles'
  ) THEN
    EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.profiles';
    RAISE NOTICE '✓ Added profiles to supabase_realtime';
  ELSE
    RAISE NOTICE '→ profiles already in supabase_realtime';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname    = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename  = 'user_credits'
  ) THEN
    EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.user_credits';
    RAISE NOTICE '✓ Added user_credits to supabase_realtime';
  ELSE
    RAISE NOTICE '→ user_credits already in supabase_realtime';
  END IF;
EXCEPTION
  WHEN insufficient_privilege THEN
    RAISE WARNING
      'Could not alter supabase_realtime publication — insufficient privilege. '
      'Enable manually: Dashboard → Database → Replication → supabase_realtime '
      '→ toggle ON profiles and user_credits.';
END $$;

-- ══════════════════════════════════════════════════════════════════════════════
-- SECTION 5 — RPC: detect_abuse_signals()
--
-- Scans the database for suspicious activity patterns and inserts new rows
-- into abuse_signals. Returns the count of NEW signals inserted.
-- Safe to call repeatedly — never creates duplicate signals within the window.
-- Called by GET /api/admin/abuse?runDetection=true when the page loads.
--
-- Detection rules:
--   1. credit_burn_rate  — >200 credits consumed by one user in 24 hours
--   2. failed_payments   — 3+ failed Razorpay orders for one user in 48 hours
--   3. referral_farming  — referral code used 5+ times in 24 hours (same referrer)
-- ══════════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.detect_abuse_signals()
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_count INTEGER := 0;
  r       RECORD;
BEGIN

  -- ── Signal 1: High credit burn rate ─────────────────────────────────────────
  FOR r IN
    SELECT
      ct.user_id,
      SUM(ABS(ct.amount))::INTEGER AS total_consumed,
      COUNT(*)::INTEGER             AS tx_count
    FROM public.credit_transactions ct
    WHERE ct.type        = 'consume'
      AND ct.created_at >= NOW() - INTERVAL '24 hours'
    GROUP BY ct.user_id
    HAVING SUM(ABS(ct.amount)) > 200
  LOOP
    IF NOT EXISTS (
      SELECT 1 FROM public.abuse_signals
      WHERE user_id     = r.user_id
        AND signal_type = 'credit_burn_rate'
        AND created_at >= NOW() - INTERVAL '24 hours'
        AND is_reviewed = FALSE
    ) THEN
      INSERT INTO public.abuse_signals (user_id, signal_type, severity, details)
      VALUES (
        r.user_id,
        'credit_burn_rate',
        CASE
          WHEN r.total_consumed > 500 THEN 'critical'
          WHEN r.total_consumed > 350 THEN 'high'
          ELSE 'medium'
        END,
        jsonb_build_object(
          'credits_consumed_24h', r.total_consumed,
          'transaction_count',    r.tx_count,
          'window_hours',         24,
          'threshold',            200
        )
      );
      v_count := v_count + 1;
    END IF;
  END LOOP;

  -- ── Signal 2: Multiple failed payment attempts ────────────────────────────────
  BEGIN
    FOR r IN
      SELECT
        ro.user_id,
        COUNT(*)::INTEGER AS failed_count
      FROM public.razorpay_orders ro
      WHERE ro.status      = 'failed'
        AND ro.created_at >= NOW() - INTERVAL '48 hours'
      GROUP BY ro.user_id
      HAVING COUNT(*) >= 3
    LOOP
      IF NOT EXISTS (
        SELECT 1 FROM public.abuse_signals
        WHERE user_id     = r.user_id
          AND signal_type = 'failed_payments'
          AND created_at >= NOW() - INTERVAL '48 hours'
          AND is_reviewed = FALSE
      ) THEN
        INSERT INTO public.abuse_signals (user_id, signal_type, severity, details)
        VALUES (
          r.user_id,
          'failed_payments',
          CASE WHEN r.failed_count >= 6 THEN 'high' ELSE 'medium' END,
          jsonb_build_object(
            'failed_attempts', r.failed_count,
            'window_hours',    48,
            'threshold',       3
          )
        );
        v_count := v_count + 1;
      END IF;
    END LOOP;
  EXCEPTION WHEN OTHERS THEN
    NULL; -- razorpay_orders table may not exist in all environments
  END;

  -- ── Signal 3: Referral farming ────────────────────────────────────────────────
  BEGIN
    FOR r IN
      SELECT
        ru.referrer_id,
        COUNT(*)::INTEGER AS referral_count
      FROM public.referral_uses ru
      WHERE ru.created_at >= NOW() - INTERVAL '24 hours'
      GROUP BY ru.referrer_id
      HAVING COUNT(*) >= 5
    LOOP
      IF NOT EXISTS (
        SELECT 1 FROM public.abuse_signals
        WHERE user_id     = r.referrer_id
          AND signal_type = 'referral_farming'
          AND created_at >= NOW() - INTERVAL '24 hours'
          AND is_reviewed = FALSE
      ) THEN
        INSERT INTO public.abuse_signals (user_id, signal_type, severity, details)
        VALUES (
          r.referrer_id,
          'referral_farming',
          CASE WHEN r.referral_count >= 10 THEN 'critical' ELSE 'high' END,
          jsonb_build_object(
            'referrals_in_24h', r.referral_count,
            'window_hours',     24,
            'threshold',        5
          )
        );
        v_count := v_count + 1;
      END IF;
    END LOOP;
  EXCEPTION WHEN undefined_table THEN
    NULL; -- referral_uses may not exist in all deployments
  END;

  RETURN v_count;
END;
$$;

-- ══════════════════════════════════════════════════════════════════════════════
-- SECTION 6 — RPC: get_abuse_signals_with_users()
--
-- Returns abuse signals joined with profile data (name, account_status).
-- Used by GET /api/admin/abuse after detection runs.
-- ══════════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.get_abuse_signals_with_users(
  p_is_reviewed  BOOLEAN  DEFAULT FALSE,
  p_signal_type  TEXT     DEFAULT NULL,
  p_severity     TEXT     DEFAULT NULL,
  p_limit        INTEGER  DEFAULT 100
)
RETURNS TABLE (
  id             UUID,
  user_id        UUID,
  signal_type    TEXT,
  severity       TEXT,
  details        JSONB,
  is_reviewed    BOOLEAN,
  review_action  TEXT,
  review_note    TEXT,
  reviewed_at    TIMESTAMPTZ,
  created_at     TIMESTAMPTZ,
  full_name      TEXT,
  username       TEXT,
  account_status TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
  SELECT
    s.id,
    s.user_id,
    s.signal_type,
    s.severity,
    s.details,
    s.is_reviewed,
    s.review_action,
    s.review_note,
    s.reviewed_at,
    s.created_at,
    p.full_name,
    p.username,
    p.account_status
  FROM public.abuse_signals s
  LEFT JOIN public.profiles p ON p.id = s.user_id
  WHERE
    (p_is_reviewed IS NULL OR s.is_reviewed  = p_is_reviewed)
    AND (p_signal_type IS NULL OR s.signal_type = p_signal_type)
    AND (p_severity    IS NULL OR s.severity    = p_severity)
  ORDER BY
    CASE s.severity
      WHEN 'critical' THEN 1
      WHEN 'high'     THEN 2
      WHEN 'medium'   THEN 3
      ELSE                 4
    END,
    s.created_at DESC
  LIMIT p_limit;
END;
$$;

-- ══════════════════════════════════════════════════════════════════════════════
-- SECTION 7 — RPC: resolve_abuse_signal()
--
-- Marks a signal as reviewed, records the admin's action and note,
-- and logs to admin_audit_log. Does NOT handle the credit deduction or
-- account status change — those are done by the existing admin_adjust_credits()
-- and admin_set_account_status() RPCs called from the same API route.
-- ══════════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.resolve_abuse_signal(
  p_signal_id UUID,
  p_admin_id  UUID,
  p_action    TEXT,   -- 'cleared' | 'warned' | 'suspended'
  p_note      TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_signal RECORD;
BEGIN
  IF p_action NOT IN ('cleared', 'warned', 'suspended') THEN
    RAISE EXCEPTION 'Invalid review action: %. Must be cleared, warned, or suspended.', p_action;
  END IF;

  SELECT * INTO v_signal
  FROM public.abuse_signals
  WHERE id = p_signal_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Abuse signal not found: %', p_signal_id;
  END IF;

  UPDATE public.abuse_signals
  SET
    is_reviewed   = TRUE,
    reviewed_by   = p_admin_id,
    reviewed_at   = NOW(),
    review_action = p_action,
    review_note   = COALESCE(p_note, '')
  WHERE id = p_signal_id;

  INSERT INTO public.admin_audit_log
    (admin_user_id, target_user_id, action, resource_type, resource_id, after_value, reason)
  VALUES (
    p_admin_id,
    v_signal.user_id,
    'resolve_abuse_signal',
    'abuse_signal',
    p_signal_id::TEXT,
    jsonb_build_object(
      'signal_type',   v_signal.signal_type,
      'severity',      v_signal.severity,
      'review_action', p_action
    ),
    p_note
  );

  RETURN jsonb_build_object(
    'success',       true,
    'signal_id',     p_signal_id,
    'review_action', p_action,
    'user_id',       v_signal.user_id
  );
END;
$$;

-- ══════════════════════════════════════════════════════════════════════════════
-- SECTION 8 — RPC: get_credit_stats()
--
-- WHY:
--   PostgREST has a hardcoded 1000-row default limit on all SELECT queries.
--   If the platform has >1000 credit_transactions, per-type aggregation
--   (signup_bonus, referral_bonus, etc.) via the JS API is silently truncated,
--   causing stats like "Signup Bonuses" to show 0 or less than real values.
--
-- FIX:
--   This RPC runs a single SQL GROUP BY aggregation inside Postgres — no row
--   limit. Returns all credit stats as a single JSONB object in one call.
--   The credits/stats API route calls this RPC first and falls back to the
--   direct-query approach (with explicit .limit(500000)) only if the RPC fails.
-- ══════════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.get_credit_stats()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_total_issued     BIGINT  := 0;
  v_total_consumed   BIGINT  := 0;
  v_avg_balance      NUMERIC := 0;
  v_user_count       BIGINT  := 0;
  v_signup_bonuses   BIGINT  := 0;
  v_referral_bonuses BIGINT  := 0;
  v_admin_grants     BIGINT  := 0;
  v_purchased        BIGINT  := 0;
BEGIN
  -- ── Overall totals from user_credits (source of truth) ───────────────────────
  BEGIN
    SELECT
      COALESCE(SUM(total_purchased), 0)::BIGINT,
      COALESCE(SUM(total_consumed),  0)::BIGINT,
      COALESCE(AVG(balance),         0)::NUMERIC,
      COUNT(*)::BIGINT
    INTO v_total_issued, v_total_consumed, v_avg_balance, v_user_count
    FROM public.user_credits;
  EXCEPTION WHEN OTHERS THEN NULL;
  END;

  -- ── Per-type totals — single SQL aggregation, no PostgREST row limit ─────────
  BEGIN
    SELECT
      COALESCE(SUM(ABS(amount)) FILTER (WHERE type = 'signup_bonus'),                      0)::BIGINT,
      COALESCE(SUM(ABS(amount)) FILTER (WHERE type = 'referral_bonus'),                    0)::BIGINT,
      COALESCE(SUM(amount)      FILTER (WHERE type = 'admin_grant'    AND amount > 0),     0)::BIGINT,
      COALESCE(SUM(amount)      FILTER (WHERE type = 'purchase'       AND amount > 0),     0)::BIGINT
    INTO v_signup_bonuses, v_referral_bonuses, v_admin_grants, v_purchased
    FROM public.credit_transactions;
  EXCEPTION WHEN OTHERS THEN NULL;
  END;

  RETURN jsonb_build_object(
    'total_issued',            COALESCE(v_total_issued,     0),
    'total_consumed',          COALESCE(v_total_consumed,   0),
    'net_in_circulation',      GREATEST(0, COALESCE(v_total_issued, 0) - COALESCE(v_total_consumed, 0)),
    'avg_balance_per_user',    ROUND(COALESCE(v_avg_balance, 0)),
    'total_signup_bonuses',    COALESCE(v_signup_bonuses,   0),
    'total_purchased',         COALESCE(v_purchased,        0),
    'total_referral_bonuses',  COALESCE(v_referral_bonuses, 0),
    'total_admin_grants',      COALESCE(v_admin_grants,     0)
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.get_credit_stats() TO authenticated;

-- ══════════════════════════════════════════════════════════════════════════════
-- SECTION 9 — VERIFY
-- Asserts that all critical objects were created or already exist.
-- ══════════════════════════════════════════════════════════════════════════════

DO $$
DECLARE
  v_test_orders  BIGINT;
  v_live_orders  BIGINT;
  v_total_orders BIGINT;
BEGIN
  -- ── profiles.account_status constraint ───────────────────────────────────────
  ASSERT (
    SELECT COUNT(*) FROM pg_constraint c
    JOIN pg_class t ON t.oid = c.conrelid
    JOIN pg_namespace n ON n.oid = t.relnamespace
    WHERE n.nspname = 'public'
      AND t.relname = 'profiles'
      AND c.contype = 'c'
      AND c.conname = 'profiles_account_status_check'
  ) = 1,
  '❌ profiles_account_status_check constraint missing — check Section 1';

  -- ── razorpay_orders.is_test ───────────────────────────────────────────────────
  ASSERT (
    SELECT COUNT(*) FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name   = 'razorpay_orders'
      AND column_name  = 'is_test'
  ) = 1,
  '❌ razorpay_orders.is_test column missing — check Section 2';

  -- ── abuse_signals table ───────────────────────────────────────────────────────
  ASSERT (
    SELECT COUNT(*) FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name   = 'abuse_signals'
  ) = 1,
  '❌ abuse_signals table missing — check Section 3';

  -- ── detect_abuse_signals ─────────────────────────────────────────────────────
  ASSERT (
    SELECT COUNT(*) FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public' AND p.proname = 'detect_abuse_signals'
  ) >= 1,
  '❌ detect_abuse_signals() RPC missing — check Section 5';

  -- ── get_abuse_signals_with_users ─────────────────────────────────────────────
  ASSERT (
    SELECT COUNT(*) FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public' AND p.proname = 'get_abuse_signals_with_users'
  ) >= 1,
  '❌ get_abuse_signals_with_users() RPC missing — check Section 6';

  -- ── resolve_abuse_signal ─────────────────────────────────────────────────────
  ASSERT (
    SELECT COUNT(*) FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public' AND p.proname = 'resolve_abuse_signal'
  ) >= 1,
  '❌ resolve_abuse_signal() RPC missing — check Section 7';

  -- ── get_credit_stats ─────────────────────────────────────────────────────────
  ASSERT (
    SELECT COUNT(*) FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public' AND p.proname = 'get_credit_stats'
  ) >= 1,
  '❌ get_credit_stats() RPC missing — check Section 8';

  -- ── Order counts (informational) ─────────────────────────────────────────────
  BEGIN
    SELECT
      COUNT(*)                              INTO v_total_orders FROM public.razorpay_orders;
    SELECT
      COUNT(*) FILTER (WHERE is_test = TRUE)  INTO v_test_orders  FROM public.razorpay_orders;
    SELECT
      COUNT(*) FILTER (WHERE is_test = FALSE) INTO v_live_orders  FROM public.razorpay_orders;
  EXCEPTION WHEN OTHERS THEN
    v_total_orders := 0; v_test_orders := 0; v_live_orders := 0;
  END;

  RAISE NOTICE '';
  RAISE NOTICE '✅ schema_part32_complete.sql applied successfully';
  RAISE NOTICE '   ────────────────────────────────────────────────';
  RAISE NOTICE '   Section 1 → profiles.account_status CHECK updated (added ''deleted'')';
  RAISE NOTICE '   Section 2 → razorpay_orders.is_test column ready';
  RAISE NOTICE '              (live: %, test: %, total: %)', v_live_orders, v_test_orders, v_total_orders;
  RAISE NOTICE '   Section 3 → abuse_signals table created (4 indexes, RLS enabled)';
  RAISE NOTICE '   Section 4 → Realtime publication updated (check notices above)';
  RAISE NOTICE '   Section 5 → detect_abuse_signals() RPC created';
  RAISE NOTICE '   Section 6 → get_abuse_signals_with_users() RPC created';
  RAISE NOTICE '   Section 7 → resolve_abuse_signal() RPC created';
  RAISE NOTICE '   Section 8 → get_credit_stats() RPC created (fixes signup bonus 0)';
  RAISE NOTICE '';
  RAISE NOTICE 'Next steps:';
  RAISE NOTICE '  1. If Realtime publication failed above, enable manually:';
  RAISE NOTICE '     Dashboard → Database → Replication → supabase_realtime';
  RAISE NOTICE '     toggle ON: profiles, user_credits';
  RAISE NOTICE '  2. Deploy the updated edge function:';
  RAISE NOTICE '     supabase functions deploy razorpay-create-order --no-verify-jwt';
  RAISE NOTICE '  3. Test payments made after edge function deploy will be tagged is_test=true';
END $$;